-- Módulo Logística — montagem de carregamentos
--
-- O supervisor liga para as distribuidoras, faz o pedido e monta a carga:
-- cabeçalho (carreta, cavalo, motorista, distribuidora, datas) e a
-- composição (posto × produto × quantidade × preço).
--
-- A distribuidora é o cadastro de Operações (fornecedores_combustiveis);
-- o produto é o de combustiveis; o posto é (cod_empresa, cod_filial).
-- Capacidade total da carreta, valor de cada linha e totais são
-- calculados na consulta — nada disso vira coluna.

-- ------------------------------------------------------------------
-- CNPJ da filial: vai no pedido, ao lado do nome do posto
-- ------------------------------------------------------------------
ALTER TABLE public.filiais ADD COLUMN IF NOT EXISTS cnpj character varying;

-- ------------------------------------------------------------------
-- Carretas: placa + capacidade de cada tanque (compartimento), em litros.
-- 12 campos fixos: uma carreta de 60 mil litros tem 12 tanques. Tanque que
-- a carreta não tem fica nulo.
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.logistica_carretas (
    id_carreta        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa       character varying NOT NULL,
    placa             character varying NOT NULL,
    tanque_01         integer,
    tanque_02         integer,
    tanque_03         integer,
    tanque_04         integer,
    tanque_05         integer,
    tanque_06         integer,
    tanque_07         integer,
    tanque_08         integer,
    tanque_09         integer,
    tanque_10         integer,
    tanque_11         integer,
    tanque_12         integer,
    ativo             boolean NOT NULL DEFAULT true,
    criado_em         timestamp without time zone DEFAULT now(),
    atualizado_em     timestamp without time zone DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_logistica_carretas_placa
    ON public.logistica_carretas (cod_empresa, placa);
ALTER TABLE public.logistica_carretas ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------------
-- Cavalos (o caminhão-trator, onde fica o motor)
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.logistica_cavalos (
    id_cavalo         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa       character varying NOT NULL,
    placa             character varying NOT NULL,
    ativo             boolean NOT NULL DEFAULT true,
    criado_em         timestamp without time zone DEFAULT now(),
    atualizado_em     timestamp without time zone DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_logistica_cavalos_placa
    ON public.logistica_cavalos (cod_empresa, placa);
ALTER TABLE public.logistica_cavalos ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------------
-- Motoristas
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.logistica_motoristas (
    id_motorista      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa       character varying NOT NULL,
    nome              character varying NOT NULL,
    cpf               character varying,
    ativo             boolean NOT NULL DEFAULT true,
    criado_em         timestamp without time zone DEFAULT now(),
    atualizado_em     timestamp without time zone DEFAULT now()
);
ALTER TABLE public.logistica_motoristas ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------------
-- Carregamento (cabeçalho). numero é sequencial por empresa.
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.logistica_carregamentos (
    id_carregamento   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa       character varying NOT NULL,
    numero            integer NOT NULL,
    data_pedido       date NOT NULL,
    data_carregamento date,
    id_carreta        integer REFERENCES public.logistica_carretas (id_carreta),
    id_cavalo         integer REFERENCES public.logistica_cavalos (id_cavalo),
    id_motorista      integer REFERENCES public.logistica_motoristas (id_motorista),
    id_fornecedor     integer REFERENCES public.fornecedores_combustiveis (id_fornecedor),
    observacao        character varying,
    id_usuario_criacao integer,
    criado_em         timestamp without time zone DEFAULT now(),
    atualizado_em     timestamp without time zone DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_logistica_carregamentos_numero
    ON public.logistica_carregamentos (cod_empresa, numero);
ALTER TABLE public.logistica_carregamentos ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------------
-- Composição do carregamento: uma linha por posto × produto.
-- codigo: código alfanumérico do pedido (ex.: E99-16).
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.logistica_carregamentos_itens (
    id_carregamento_item integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa       character varying NOT NULL,
    id_carregamento   integer NOT NULL
                      REFERENCES public.logistica_carregamentos (id_carregamento)
                      ON DELETE CASCADE,
    cod_filial        integer NOT NULL,
    cod_produto       character varying NOT NULL,
    quantidade        numeric(14,3) NOT NULL DEFAULT 0,
    preco_unitario    numeric(14,4) NOT NULL DEFAULT 0,
    codigo            character varying,
    ordem             integer DEFAULT 10,
    criado_em         timestamp without time zone DEFAULT now(),
    atualizado_em     timestamp without time zone DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_logistica_itens_carregamento
    ON public.logistica_carregamentos_itens (id_carregamento);
ALTER TABLE public.logistica_carregamentos_itens ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------------
-- Permissões. Não concede a ninguém: só o superusuário passa por bypass.
-- O Preço de Compra continua sendo OPERACOES/INFORMAR_PRECO_COMPRA — é a
-- mesma tela, com o mesmo dono.
-- ------------------------------------------------------------------
INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo) VALUES
    ('LOGISTICA', 'MENU',          'Menu de Logística',               2000, true),
    ('LOGISTICA', 'CARREGAMENTOS', 'Montar Carregamentos',            2010, true),
    ('LOGISTICA', 'CONFIGURACOES', 'Configurações de Logística',      2020, true)
ON CONFLICT DO NOTHING;
