-- =====================================================================
-- Módulo Saldos (Matrix / Financeiro) — criação das tabelas novas
-- PostgreSQL / Supabase — encaixado no schema existente (empresa EMP010)
-- =====================================================================

-- ============================================================
-- Garantia de integridade (idempotente — só cria se não existir)
-- Necessário para poder referenciar filiais por (cod_empresa, cod_filial)
-- ============================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'filiais_cod_empresa_cod_filial_key'
  ) THEN
    ALTER TABLE filiais
      ADD CONSTRAINT filiais_cod_empresa_cod_filial_key UNIQUE (cod_empresa, cod_filial);
  END IF;
END $$;

-- ============================================================
-- CADASTROS NOVOS
-- ============================================================

-- Contas bancárias, por EMPRESA (não por área — todas as áreas compartilham o mesmo conjunto de bancos)
CREATE TABLE contas_bancarias (
    id_conta_bancaria  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa        character varying NOT NULL,
    banco              character varying NOT NULL,   -- 'Banco do Brasil', 'Itaú', 'Bradesco', 'Saldo Conta/WEB', ...
    apelido            character varying,             -- opcional, se houver 2 contas do mesmo banco
    ordem              integer DEFAULT 10,
    ativo              boolean NOT NULL DEFAULT true,
    criado_em          timestamp without time zone DEFAULT now(),
    atualizado_em      timestamp without time zone DEFAULT now(),
    UNIQUE (cod_empresa, banco, apelido)
);

-- Cadastro de indicadores do bloco "Estoques e recebíveis" (por EMPRESA, igual contas_bancarias)
CREATE TABLE indicadores_recebiveis (
    id_indicador_recebivel  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa             character varying NOT NULL,
    nome                    character varying NOT NULL,   -- 'Cartões de Crédito', 'Fiado', 'Cheque', 'Compra Combustível', 'Em Trânsito', 'Estoque', ...
    ordem                   integer DEFAULT 10,
    ativo                   boolean NOT NULL DEFAULT true,
    criado_em               timestamp without time zone DEFAULT now(),
    atualizado_em           timestamp without time zone DEFAULT now(),
    UNIQUE (cod_empresa, nome)
);

-- Data de corte de competência (fechamento de mês), por área
CREATE TABLE competencia_mes (
    id_competencia      integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa         character varying NOT NULL,
    id_area             integer NOT NULL REFERENCES areas (id_area),
    mes_ano             date NOT NULL,          -- normalizado para o dia 1 do mês, ex. 2026-06-01
    data_corte_inicio   date NOT NULL,          -- ex. 2026-05-29 (último dia válido do mês anterior)
    criado_em           timestamp without time zone DEFAULT now(),
    atualizado_em       timestamp without time zone DEFAULT now(),
    UNIQUE (cod_empresa, id_area, mes_ano)
);

-- ============================================================
-- LANÇAMENTOS DIÁRIOS (editáveis na tela de Saldos)
-- ============================================================

-- Bloco "Contas bancárias": saldo banco x saldo sistema, por conta e filial
CREATE TABLE saldos_bancarios (
    id_saldo_bancario   integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa         character varying NOT NULL,
    cod_filial          integer NOT NULL,
    data                date NOT NULL,
    id_conta_bancaria   integer NOT NULL REFERENCES contas_bancarias (id_conta_bancaria),
    saldo_banco         numeric NOT NULL DEFAULT 0,
    saldo_sistema       numeric NOT NULL DEFAULT 0,
    usuario_lancamento  integer REFERENCES usuarios (id_usuario),
    criado_em           timestamp without time zone DEFAULT now(),
    atualizado_em       timestamp without time zone DEFAULT now(),
    UNIQUE (cod_empresa, cod_filial, data, id_conta_bancaria),
    FOREIGN KEY (cod_empresa, cod_filial) REFERENCES filiais (cod_empresa, cod_filial)
);

-- Bloco "Estoques e recebíveis" — referencia o cadastro de indicadores, não um valor fixo
CREATE TABLE saldos_recebiveis (
    id_saldo_recebivel      integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa             character varying NOT NULL,
    cod_filial              integer NOT NULL,
    data                    date NOT NULL,
    id_indicador_recebivel  integer NOT NULL REFERENCES indicadores_recebiveis (id_indicador_recebivel),
    valor_banco             numeric NOT NULL DEFAULT 0,    -- lado "Bancos" da planilha (ex.: estoque a preço de custo)
    valor_sistema           numeric NOT NULL DEFAULT 0,    -- lado "WEB" da planilha
    usuario_lancamento      integer REFERENCES usuarios (id_usuario),
    criado_em               timestamp without time zone DEFAULT now(),
    atualizado_em           timestamp without time zone DEFAULT now(),
    UNIQUE (cod_empresa, cod_filial, data, id_indicador_recebivel),
    FOREIGN KEY (cod_empresa, cod_filial) REFERENCES filiais (cod_empresa, cod_filial)
);

-- Bloco "Valores informados"
CREATE TABLE valores_informados (
    id_valor_informado       integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa              character varying NOT NULL,
    cod_filial               integer NOT NULL,
    data                     date NOT NULL,
    perdas_sobras            numeric NOT NULL DEFAULT 0,  -- perdas(+) / sobras(-)
    extras                   numeric NOT NULL DEFAULT 0,  -- aportes/aplicações
    emprestimos_devolucoes   numeric NOT NULL DEFAULT 0,  -- empréstimos(+) / devoluções(-)
    despesas                 numeric NOT NULL DEFAULT 0,
    usuario_lancamento       integer REFERENCES usuarios (id_usuario),
    criado_em                timestamp without time zone DEFAULT now(),
    atualizado_em            timestamp without time zone DEFAULT now(),
    UNIQUE (cod_empresa, cod_filial, data),
    FOREIGN KEY (cod_empresa, cod_filial) REFERENCES filiais (cod_empresa, cod_filial)
);

-- ============================================================
-- ÍNDICES DE APOIO (consulta por período é a query mais comum da tela)
-- ============================================================
CREATE INDEX idx_saldos_bancarios_data ON saldos_bancarios (cod_empresa, data);
CREATE INDEX idx_saldos_recebiveis_data ON saldos_recebiveis (cod_empresa, data);
CREATE INDEX idx_indicadores_recebiveis_empresa ON indicadores_recebiveis (cod_empresa);
CREATE INDEX idx_valores_informados_data ON valores_informados (cod_empresa, data);

-- ============================================================
-- RLS — bloqueia acesso direto via chave anônima/pública; tudo passa pela API
-- (que usa a service role key, mesmo padrão do restante do banco)
-- ============================================================
ALTER TABLE contas_bancarias       ENABLE ROW LEVEL SECURITY;
ALTER TABLE indicadores_recebiveis ENABLE ROW LEVEL SECURITY;
ALTER TABLE competencia_mes        ENABLE ROW LEVEL SECURITY;
ALTER TABLE saldos_bancarios       ENABLE ROW LEVEL SECURITY;
ALTER TABLE saldos_recebiveis      ENABLE ROW LEVEL SECURITY;
ALTER TABLE valores_informados     ENABLE ROW LEVEL SECURITY;

CREATE POLICY service_role_only ON contas_bancarias       FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY service_role_only ON indicadores_recebiveis FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY service_role_only ON competencia_mes        FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY service_role_only ON saldos_bancarios        FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY service_role_only ON saldos_recebiveis       FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY service_role_only ON valores_informados      FOR ALL TO service_role USING (true) WITH CHECK (true);
