-- PDV Matrix — fase 5: Caixa Central de Vendas.
--
-- A venda continua definitivamente fechada. O Caixa Central existe para o
-- Financeiro CONFERIR o dia e corrigir informações **complementares** do
-- recebimento — a operadora de cartão registrada errada, a quantidade de
-- parcelas digitada diferente do que passou na maquineta.
--
-- O que NUNCA muda por aqui: produto, quantidade, preço, cliente, vendedor,
-- valor total da venda e valor total recebido. Corrigir um atributo do
-- recebimento não é reabrir a venda.
--
-- E toda correção deixa rastro: valor anterior, valor novo, quem fez, quando.
-- É isso que separa "corrigir uma classificação" de "alterar uma venda".

CREATE TABLE IF NOT EXISTS public.pdv_caixa_central_auditoria (
    id_pdv_caixa_auditoria integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    id_pdv_venda integer NOT NULL REFERENCES public.pdv_vendas (id_pdv_venda),
    id_pdv_venda_recebimento integer
        REFERENCES public.pdv_vendas_recebimentos (id_pdv_venda_recebimento),
    -- o atributo corrigido: id_pdv_operadora | qtd_parcelas
    campo character varying NOT NULL,
    valor_anterior character varying,
    valor_novo character varying,
    -- guardados por extenso para o histórico continuar legível mesmo que o
    -- cadastro mude de nome depois
    descricao_anterior character varying,
    descricao_nova character varying,
    id_usuario integer,
    nome_usuario character varying,
    alterado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_caixa_central_auditoria ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS ix_pdv_caixa_auditoria_venda
    ON public.pdv_caixa_central_auditoria (cod_empresa, id_pdv_venda);
CREATE INDEX IF NOT EXISTS ix_pdv_caixa_auditoria_data
    ON public.pdv_caixa_central_auditoria (cod_empresa, alterado_em);
