-- =====================================================================
-- Caixas — quem consulta e quem altera, por área
--
-- Duas permissões distintas, concedidas por área:
--   pode_consultar : vê a área, sem digitar
--   pode_alterar   : digita nas filiais daquela área (implica consultar)
--
-- A linha com id_area NULL é o resumo consolidado de TODAS as áreas. Ali só
-- faz sentido consultar: alterar é sempre dentro de uma área específica.
-- Por isso a chave única usa COALESCE — no Postgres, NULL não conflita com
-- NULL, e sem isso dava para gravar o resumo duas vezes para o mesmo
-- usuário.
--
-- Superusuário não entra aqui: continua podendo tudo, sem precisar de linha.
--
-- Esta migração só cria o cadastro. A tela de Conferir Caixas ainda não
-- consulta esta tabela — isso é o passo seguinte.
-- =====================================================================

CREATE TABLE caixas_acessos (
    id_caixa_acesso  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa      character varying NOT NULL,
    id_usuario       integer NOT NULL REFERENCES usuarios (id_usuario),
    id_area          integer REFERENCES areas (id_area),
    pode_consultar   boolean NOT NULL DEFAULT false,
    pode_alterar     boolean NOT NULL DEFAULT false,
    criado_em        timestamp without time zone NOT NULL DEFAULT now(),
    atualizado_em    timestamp without time zone NOT NULL DEFAULT now(),

    -- alterar sem poder consultar não faz sentido
    CONSTRAINT caixas_acessos_alterar_implica_consultar
        CHECK (NOT pode_alterar OR pode_consultar),

    -- no resumo de todas as áreas não se altera nada
    CONSTRAINT caixas_acessos_resumo_nao_altera
        CHECK (id_area IS NOT NULL OR NOT pode_alterar)
);

CREATE UNIQUE INDEX caixas_acessos_unico
    ON caixas_acessos (cod_empresa, id_usuario, COALESCE(id_area, -1));

CREATE INDEX idx_caixas_acessos_usuario
    ON caixas_acessos (cod_empresa, id_usuario);

ALTER TABLE caixas_acessos ENABLE ROW LEVEL SECURITY;

CREATE POLICY service_role_only ON caixas_acessos
    FOR ALL TO service_role USING (true) WITH CHECK (true);

INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo) VALUES
    ('FINANCEIRO', 'ACESSOS_CAIXAS', 'Acessos de Caixas', 504, true);
