-- =====================================================================
-- Conferir Caixas — observação livre do dia
--
-- Texto solto, um por (empresa, filial, data), digitado no fim do painel
-- de detalhamento (✎) e exibido também no painel de consulta (👁).
--
-- Não é a observação de uma linha de detalhe (essa vive em
-- caixas_lancamentos_detalhe / caixas_controles_detalhe, colada a um
-- valor): aqui é o recado do dia inteiro, sem valor associado.
-- =====================================================================

CREATE TABLE caixas_observacoes_dia (
    id             integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa    character varying NOT NULL,
    cod_filial     integer NOT NULL,
    data           date NOT NULL,
    observacao     text NOT NULL DEFAULT '',
    criado_em      timestamp without time zone NOT NULL DEFAULT now(),
    atualizado_em  timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT caixas_observacoes_dia_unica
        UNIQUE (cod_empresa, cod_filial, data)
);

CREATE INDEX idx_caixas_observacoes_dia_filial
    ON caixas_observacoes_dia (cod_empresa, cod_filial, data);

ALTER TABLE caixas_observacoes_dia ENABLE ROW LEVEL SECURITY;

CREATE POLICY service_role_only ON caixas_observacoes_dia
    FOR ALL TO service_role USING (true) WITH CHECK (true);
