-- Parâmetros do módulo de Vendas, uma linha por empresa.
-- Hoje guarda só a origem da importação do painel; novas opções entram como
-- colunas nesta mesma linha.

CREATE TABLE IF NOT EXISTS vendas_parametros (
    id_vendas_parametro integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL UNIQUE,
    sistema_origem_painel character varying NOT NULL DEFAULT 'WEBPOSTOS',
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);

ALTER TABLE vendas_parametros ENABLE ROW LEVEL SECURITY;

INSERT INTO vendas_parametros (cod_empresa, sistema_origem_painel)
VALUES
    ('EMP010', 'WEBPOSTOS'),
    ('EMP011', 'WEBPOSTOS'),
    ('EMP011ADM', 'WEBPOSTOS'),
    ('EMP012', 'WEBPOSTOS'),
    ('EMP013', 'OCLOSET')
ON CONFLICT (cod_empresa) DO NOTHING;

INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo)
SELECT 'VENDAS', 'PARAMETROS', 'Parâmetros de Vendas', 770, TRUE
WHERE NOT EXISTS (
    SELECT 1 FROM permissoes_catalogo
    WHERE sistema = 'VENDAS' AND opcao = 'PARAMETROS'
);
