-- Dias especiais da Agenda (Canivete Suíço)
--
-- Feriado nacional é calculado (_feriados); isto aqui é o dia que o próprio
-- usuário marca como especial clicando no número na grade — ponte, folga,
-- viagem. Por isso a chave é id_usuario, não empresa: a agenda é pessoal.
--
-- Uma linha = dia marcado; desmarcar apaga a linha (mesmo desenho de
-- operacoes_bloqueios).

CREATE TABLE IF NOT EXISTS agenda_dias_especiais (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario integer NOT NULL,
    data       date    NOT NULL,
    criado_em  timestamp without time zone DEFAULT now(),
    CONSTRAINT uq_agenda_dias_especiais UNIQUE (id_usuario, data)
);

ALTER TABLE public.agenda_dias_especiais ENABLE ROW LEVEL SECURITY;
