-- =====================================================================
-- Módulo Saldos (Matrix / Financeiro) — liberação temporária de datas antigas
-- Regra normal: só é possível lançar/editar ontem e anteontem. Um usuário com
-- CADASTRO_CONTAS_BANCARIAS pode liberar temporariamente a edição a partir de
-- uma data mais antiga (ex.: "liberar desde o dia 1"). A liberação expira
-- sozinha 1 hora depois de ativada (checado por horário, sem rotina em
-- background) — depois disso volta a valer a regra normal.
-- =====================================================================

CREATE TABLE saldos_liberacao_temporaria (
    id_liberacao        integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa         character varying NOT NULL,
    data_liberada_desde date NOT NULL,
    ativado_em          timestamp without time zone NOT NULL DEFAULT now(),
    id_usuario_ativou   integer REFERENCES usuarios (id_usuario),
    criado_em           timestamp without time zone DEFAULT now()
);

CREATE INDEX idx_saldos_liberacao_temporaria_empresa ON saldos_liberacao_temporaria (cod_empresa, ativado_em DESC);

ALTER TABLE saldos_liberacao_temporaria ENABLE ROW LEVEL SECURITY;

CREATE POLICY service_role_only ON saldos_liberacao_temporaria FOR ALL TO service_role USING (true) WITH CHECK (true);
