-- =====================================================================
-- Módulo Saldos (Matrix / Financeiro) — informações adicionais
-- Uma linha por empresa, com as opções que ligam/desligam partes da tela
-- de Informar Saldos. Editada em Saldos → Configurar Saldos →
-- Informações Adicionais.
--
-- Cada coluna mostrar_* liga/desliga um bloco da tela de Informar Saldos.
-- Empresa sem linha aqui é tratada como tudo desligado.
--   mostrar_valores_informados: bloco "Valores Informados" (Perdas/Sobras,
--     Extras, Empréstimos/Devoluções, Despesas e Variação Final)
--   mostrar_recebiveis: bloco "Estoques e Recebíveis" (e, com ele, a linha
--     de TOTAL, que só faz sentido somando os dois blocos)
--   mostrar_variacoes: bloco "Variação (dia a dia)"
-- =====================================================================

CREATE TABLE saldos_configuracoes (
    id_saldos_configuracao      integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa                 character varying NOT NULL,
    mostrar_valores_informados  boolean NOT NULL DEFAULT false,
    mostrar_recebiveis          boolean NOT NULL DEFAULT false,
    mostrar_variacoes           boolean NOT NULL DEFAULT false,
    criado_em                   timestamp without time zone DEFAULT now(),
    atualizado_em               timestamp without time zone DEFAULT now(),
    CONSTRAINT uq_saldos_configuracoes_empresa UNIQUE (cod_empresa)
);

ALTER TABLE saldos_configuracoes ENABLE ROW LEVEL SECURITY;

CREATE POLICY service_role_only ON saldos_configuracoes FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Lucena usa a tela completa; as demais empresas só as Contas Bancárias.
INSERT INTO saldos_configuracoes
    (cod_empresa, mostrar_valores_informados, mostrar_recebiveis, mostrar_variacoes)
VALUES
    ('EMP010',    true,  true,  true),
    ('EMP011',    false, false, false),
    ('EMP011ADM', false, false, false),
    ('EMP012',    false, false, false)
ON CONFLICT (cod_empresa) DO NOTHING;
