-- Parâmetros do PDV Matrix, uma linha por empresa.
--
-- Hoje guarda só "esta empresa opera com PDV". É uma trava de proteção: o PDV
-- é módulo novo e mexe em venda e caixa, então empresa nenhuma o enxerga por
-- padrão — nem o superusuário. Empresa sem linha aqui = NÃO opera com PDV.
--
-- Opção nova entra como coluna nesta mesma linha.

CREATE TABLE IF NOT EXISTS public.pdv_parametros (
    id_pdv_parametro integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL UNIQUE,
    opera_pdv boolean NOT NULL DEFAULT FALSE,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);

ALTER TABLE public.pdv_parametros ENABLE ROW LEVEL SECURITY;

-- Tela: Configurações → Configuração de PDV
INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo)
SELECT 'CONFIGURACOES', 'CONFIGURACAO_PDV', 'Configuração de PDV', 1720, TRUE
WHERE NOT EXISTS (
    SELECT 1 FROM permissoes_catalogo
    WHERE sistema = 'CONFIGURACOES' AND opcao = 'CONFIGURACAO_PDV'
);

-- Nenhuma empresa é ativada aqui, de propósito: a ativação é feita pela tela,
-- empresa por empresa.
