-- PDV Matrix — Campanhas (preço promocional).
--
--     Campanha (nome + período + desconto)
--       ↓
--     Itens da Campanha (carregados por filtro: marca, categoria ou todos)
--       ↓
--     Venda dentro do período → usa o preço promocional
--
-- O que se guarda por item é o **percentual de desconto**, que é a decisão
-- tomada. O preço promocional é calculado a partir dele
-- (`preco_venda × (1 − desconto)`) — pela mesma regra de sempre: valor
-- derivado não vira coluna. O preço que efetivamente valeu na venda fica
-- gravado em `pdv_vendas_itens.preco_unitario`, como já era.
--
-- Fora do período a campanha simplesmente não vale: nada precisa ser
-- desfeito quando ela termina.

CREATE TABLE IF NOT EXISTS public.pdv_campanhas (
    id_pdv_campanha integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    nome character varying NOT NULL,
    data_inicio date NOT NULL,
    data_fim date NOT NULL,
    -- desconto sugerido ao carregar os itens; cada item pode ter o seu
    percentual_desconto numeric(6,2) NOT NULL DEFAULT 0,
    observacao text,
    ativo boolean NOT NULL DEFAULT TRUE,
    ordem integer DEFAULT 10,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_campanhas ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_campanhas_periodo
    ON public.pdv_campanhas (cod_empresa, ativo, data_inicio, data_fim);


CREATE TABLE IF NOT EXISTS public.pdv_campanhas_itens (
    id_pdv_campanha_item integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    id_pdv_campanha integer NOT NULL
        REFERENCES public.pdv_campanhas (id_pdv_campanha) ON DELETE CASCADE,
    id_pdv_produto integer NOT NULL REFERENCES public.pdv_produtos (id_pdv_produto),
    percentual_desconto numeric(6,2) NOT NULL DEFAULT 0,
    criado_em timestamp without time zone DEFAULT now(),
    -- o mesmo produto não entra duas vezes na mesma campanha
    CONSTRAINT uq_pdv_campanha_produto UNIQUE (id_pdv_campanha, id_pdv_produto)
);
ALTER TABLE public.pdv_campanhas_itens ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_campanhas_itens_produto
    ON public.pdv_campanhas_itens (cod_empresa, id_pdv_produto);


-- Por qual campanha o item da venda saiu, quando saiu por uma. É o que
-- responde depois "quanto foi vendido em campanha".
ALTER TABLE public.pdv_vendas_itens
    ADD COLUMN IF NOT EXISTS id_pdv_campanha integer
        REFERENCES public.pdv_campanhas (id_pdv_campanha);


INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo)
SELECT 'PDV', v.opcao, v.descricao, v.ordem, TRUE
FROM (VALUES
    ('CAMPANHAS_MENU',  'Menu de Campanhas',          1880),
    ('CAMPANHAS',       'Cadastrar Campanhas',        1890),
    ('CAMPANHAS_ITENS', 'Itens das Campanhas',        1900)
) AS v(opcao, descricao, ordem)
WHERE NOT EXISTS (
    SELECT 1 FROM permissoes_catalogo p
    WHERE p.sistema = 'PDV' AND p.opcao = v.opcao
);


-- ─── SITUAÇÃO DA CAMPANHA ────────────────────────────────────────────────────
-- Uma campanha pode ser interrompida antes do término, e são dois casos
-- diferentes:
--
--   ATIVA     → vale enquanto o dia estiver dentro do período
--   PAUSADA   → suspensa temporariamente; volta a valer ao ser retomada
--   ENCERRADA → terminou antes da data prevista. Ao encerrar, `data_fim`
--               recebe a data de hoje, para o período gravado refletir o que
--               de fato valeu.
--
-- Substitui o `ativo` booleano: com três estados, dois flags separados
-- acabariam se contradizendo.

ALTER TABLE public.pdv_campanhas
    ADD COLUMN IF NOT EXISTS situacao character varying NOT NULL DEFAULT 'ATIVA';

UPDATE public.pdv_campanhas
   SET situacao = CASE WHEN ativo THEN 'ATIVA' ELSE 'PAUSADA' END
 WHERE situacao IS NULL;

ALTER TABLE public.pdv_campanhas DROP COLUMN IF EXISTS ativo;
