-- Coligadas: empresas da família / grupo econômico que NÃO pertencem ao grupo
-- a ponto de controlarmos estoque, perda e sobra delas.
--
-- A ponta de uma compra e a ponta de um descarrego passam a ser
-- "uma filial nossa OU uma coligada" — é isso que permite comprar pela
-- coligada e descarregar aqui (fico devendo a ela) e o inverso.
--
-- Não há parâmetro "trabalha com coligadas": empresa com coligada ativa
-- cadastrada trabalha com coligadas. Um flag separado seria uma segunda
-- verdade, que diverge da tabela na primeira manutenção.

CREATE TABLE IF NOT EXISTS public.operacoes_coligadas (
    id_coligada     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa     character varying NOT NULL,
    nome            character varying NOT NULL,
    nome_fantasia   character varying,
    cnpj            character varying,
    ativo           boolean NOT NULL DEFAULT TRUE,
    ordem           integer DEFAULT 10,
    criado_em       timestamp without time zone DEFAULT now(),
    atualizado_em   timestamp without time zone DEFAULT now()
);

ALTER TABLE public.operacoes_coligadas ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS ix_operacoes_coligadas_empresa
    ON public.operacoes_coligadas (cod_empresa, ativo);

-- ---------------------------------------------------------------
-- A ponta da compra
-- ---------------------------------------------------------------
ALTER TABLE public.compras_combustiveis
    ADD COLUMN IF NOT EXISTS id_coligada integer
        REFERENCES public.operacoes_coligadas (id_coligada);

ALTER TABLE public.compras_combustiveis
    ALTER COLUMN cod_filial DROP NOT NULL;

-- exatamente uma das duas pontas
ALTER TABLE public.compras_combustiveis
    DROP CONSTRAINT IF EXISTS ck_compras_parte;

ALTER TABLE public.compras_combustiveis
    ADD CONSTRAINT ck_compras_parte CHECK (
        (cod_filial IS NOT NULL AND id_coligada IS NULL)
     OR (cod_filial IS NULL     AND id_coligada IS NOT NULL)
    );

-- ---------------------------------------------------------------
-- A ponta do descarrego
-- ---------------------------------------------------------------
ALTER TABLE public.descarregos_combustiveis
    ADD COLUMN IF NOT EXISTS id_coligada integer
        REFERENCES public.operacoes_coligadas (id_coligada);

ALTER TABLE public.descarregos_combustiveis
    ALTER COLUMN cod_filial_descarga DROP NOT NULL;

ALTER TABLE public.descarregos_combustiveis
    DROP CONSTRAINT IF EXISTS ck_descarregos_parte;

ALTER TABLE public.descarregos_combustiveis
    ADD CONSTRAINT ck_descarregos_parte CHECK (
        (cod_filial_descarga IS NOT NULL AND id_coligada IS NULL)
     OR (cod_filial_descarga IS NULL     AND id_coligada IS NOT NULL)
    );

-- ---------------------------------------------------------------
-- O índice único de compras inclui a coligada: a mesma data/produto/
-- fornecedor pode ter um pedido meu e um pedido da coligada.
-- ---------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS uq_compras_combustiveis_coligada
    ON public.compras_combustiveis
       (cod_empresa, data_compra, id_coligada, cod_produto, id_fornecedor)
    WHERE id_coligada IS NOT NULL;
