-- Antecipação de dividendos: dinheiro retirado das contas, informado por
-- filial e data. Entra na tela de Variações para explicar a queda de saldo.

CREATE TABLE IF NOT EXISTS antecipacao_dividendos (
    id_antecipacao      integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa         character varying NOT NULL,
    cod_filial          integer NOT NULL,
    data                date NOT NULL,
    valor               numeric(14,2) NOT NULL DEFAULT 0,
    usuario_lancamento  integer,
    criado_em           timestamp without time zone DEFAULT now(),
    atualizado_em       timestamp without time zone DEFAULT now(),
    UNIQUE (cod_empresa, cod_filial, data)
);

CREATE INDEX IF NOT EXISTS idx_antecipacao_dividendos_data
    ON antecipacao_dividendos (cod_empresa, data);

ALTER TABLE antecipacao_dividendos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS service_role_only ON antecipacao_dividendos;
CREATE POLICY service_role_only ON antecipacao_dividendos
    FOR ALL TO service_role USING (true) WITH CHECK (true);

INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo) VALUES
    ('FINANCEIRO', 'ANTECIPACAO_DIVIDENDOS', 'Informar Antecipação de Dividendos', 511, true)
ON CONFLICT DO NOTHING;
