-- =====================================================================
-- Módulo Caixas (Matrix / Financeiro) — liberação temporária de datas antigas
-- Regra normal: só é possível digitar os últimos DIAS_EDICAO_CAIXA dias.
-- Um usuário com CONFIGURACOES_CAIXAS pode liberar temporariamente a edição
-- a partir de uma data mais antiga. A liberação expira sozinha algumas horas
-- depois de ativada (checado por horário, sem rotina em background) — depois
-- disso volta a valer a janela normal. Mesmo desenho de
-- saldos_liberacao_temporaria.
-- =====================================================================

CREATE TABLE caixas_liberacao_temporaria (
    id_liberacao        integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa         character varying NOT NULL,
    data_liberada_desde date NOT NULL,
    ativado_em          timestamp without time zone NOT NULL DEFAULT now(),
    id_usuario_ativou   integer REFERENCES usuarios (id_usuario),
    criado_em           timestamp without time zone DEFAULT now()
);

CREATE INDEX idx_caixas_liberacao_temporaria_empresa ON caixas_liberacao_temporaria (cod_empresa, ativado_em DESC);

ALTER TABLE caixas_liberacao_temporaria ENABLE ROW LEVEL SECURITY;

CREATE POLICY service_role_only ON caixas_liberacao_temporaria FOR ALL TO service_role USING (true) WITH CHECK (true);
