-- Detalhamento analitico do Fluxo de Caixa (WebPostos - Tipo: Analitico)
--
-- Espelha o par importacoes -> lancamentos:
--   importacoes_detalhamento  = temporaria, enchida pela importacao
--   lancamentos_detalhamento  = definitiva, so recebe na transferencia
--
-- As duas andam SEMPRE junto com a sintetica correspondente: quem apaga
-- importacoes apaga importacoes_detalhamento na mesma transacao.

CREATE TABLE IF NOT EXISTS public.importacoes_detalhamento (
    id_detalhamento   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa       character varying NOT NULL,
    cod_filial        integer NOT NULL,
    nome_filial       character varying,
    ano               integer NOT NULL,
    mes               integer NOT NULL,
    data              date,
    codigo_conta      character varying NOT NULL,
    historico_conta   character varying NOT NULL,
    descricao         character varying,
    valor             numeric(14,2) NOT NULL DEFAULT 0,
    grupo             character varying,
    conta             character varying,
    descricao_conta   character varying,
    complemento       character varying,
    criado_em         timestamp without time zone DEFAULT now(),
    atualizado_em     timestamp without time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.lancamentos_detalhamento (
    id_detalhamento   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa       character varying NOT NULL,
    cod_filial        integer NOT NULL,
    nome_filial       character varying,
    ano               integer NOT NULL,
    mes               integer NOT NULL,
    data              date,
    codigo_conta      character varying NOT NULL,
    historico_conta   character varying NOT NULL,
    descricao         character varying,
    valor             numeric(14,2) NOT NULL DEFAULT 0,
    grupo             character varying,
    conta             character varying,
    descricao_conta   character varying,
    complemento       character varying,
    criado_em         timestamp without time zone DEFAULT now(),
    atualizado_em     timestamp without time zone DEFAULT now()
);

-- indice da chave que a celula do matricial usa para abrir o detalhamento
CREATE INDEX IF NOT EXISTS ix_importacoes_detalhamento_chave
    ON public.importacoes_detalhamento (cod_empresa, cod_filial, ano, mes, grupo, conta);

CREATE INDEX IF NOT EXISTS ix_importacoes_detalhamento_conta
    ON public.importacoes_detalhamento (cod_empresa, cod_filial, ano, mes, codigo_conta);

CREATE INDEX IF NOT EXISTS ix_lancamentos_detalhamento_chave
    ON public.lancamentos_detalhamento (cod_empresa, cod_filial, ano, mes, grupo, conta);

CREATE INDEX IF NOT EXISTS ix_lancamentos_detalhamento_conta
    ON public.lancamentos_detalhamento (cod_empresa, cod_filial, ano, mes, codigo_conta);

ALTER TABLE public.importacoes_detalhamento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lancamentos_detalhamento ENABLE ROW LEVEL SECURITY;
