-- =====================================================================
-- Operações — bloqueio de movimentações por data
--
-- Uma linha = aquela data está BLOQUEADA para a empresa inteira: ninguém
-- altera medições, preços de compra, compras ou descarregos daquele dia
-- (as telas continuam abrindo, só não gravam). Desbloquear = apagar a linha.
--
-- É também o que libera a importação dos valores de estoque para o módulo
-- Financeiro → Saldos (ver criar_importacao_estoque_saldos.sql).
-- =====================================================================

CREATE TABLE operacoes_bloqueios (
    id_bloqueio     integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa     character varying NOT NULL,
    data            date NOT NULL,
    id_usuario      integer,
    criado_em       timestamp without time zone DEFAULT now(),
    atualizado_em   timestamp without time zone DEFAULT now(),
    CONSTRAINT uq_operacoes_bloqueios_empresa_data UNIQUE (cod_empresa, data)
);

CREATE INDEX idx_operacoes_bloqueios_empresa_data ON operacoes_bloqueios (cod_empresa, data);

ALTER TABLE operacoes_bloqueios ENABLE ROW LEVEL SECURITY;

CREATE POLICY service_role_only ON operacoes_bloqueios FOR ALL TO service_role USING (true) WITH CHECK (true);

INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo)
VALUES ('OPERACOES', 'BLOQUEAR_MOVIMENTACOES', 'Bloquear Movimentações', 490, TRUE)
ON CONFLICT DO NOTHING;
