-- Crédito — sócios / proprietários da empresa analisada.
--
-- Só faz sentido quando `credito_analises.tipo_cliente = 'PJ'`: a análise de
-- uma pessoa jurídica passa por quem está atrás dela. São várias pessoas por
-- análise, então é tabela filha, não colunas na análise (repetir
-- socio1_/socio2_ limitaria a quantidade e deixaria o formulário mentindo).
--
-- `situacao` REGULAR | IRREGULAR — irregular exige `situacao_motivo`, que é o
-- que explica a restrição depois. Nada de campo derivado.

CREATE TABLE IF NOT EXISTS public.credito_analises_socios (
    id_socio integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    id_analise integer NOT NULL
        REFERENCES public.credito_analises (id_analise) ON DELETE CASCADE,

    nome character varying,
    cpf character varying,
    situacao character varying,                 -- REGULAR | IRREGULAR
    situacao_motivo text,                       -- só quando IRREGULAR
    telefone character varying,

    -- Endereço completo
    cep character varying,
    logradouro character varying,
    numero character varying,
    complemento character varying,
    bairro character varying,
    cidade character varying,
    uf character varying,

    processos_judiciais text,

    ordem integer DEFAULT 10,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_credito_socios_analise
    ON public.credito_analises_socios (cod_empresa, id_analise);

ALTER TABLE public.credito_analises_socios ENABLE ROW LEVEL SECURITY;
