-- =====================================================================
-- Módulo Projetos — Estratégia
-- Mesmo padrão do cadastro de Compliance: título + texto livre colado,
-- acumulando um registro por estratégia. Acesso pela permissão do módulo
-- (PROJETOS/MENU), como as demais telas de Projetos — sem permissão própria.
-- =====================================================================

CREATE TABLE projetos_estrategias (
    id             integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa    character varying NOT NULL,
    titulo         character varying NOT NULL,
    descricao      text NOT NULL,
    ativo          boolean NOT NULL DEFAULT true,
    criado_em      timestamp without time zone DEFAULT now(),
    atualizado_em  timestamp without time zone DEFAULT now()
);

CREATE INDEX idx_projetos_estrategias_empresa ON projetos_estrategias (cod_empresa, ativo);

ALTER TABLE projetos_estrategias ENABLE ROW LEVEL SECURITY;

CREATE POLICY service_role_only ON projetos_estrategias FOR ALL TO service_role USING (true) WITH CHECK (true);
