-- Metas de vendas em quantidade (litros), por posto e mês.
--
-- Informadas em Performances → Performance de Gerentes → Metas, e lidas pela
-- tela de Vendas do gerente, que compara a venda projetada do mês com a meta.
-- Percentual atingido nunca é coluna: é calculado na consulta.

CREATE TABLE IF NOT EXISTS vendas_metas (
    id_vendas_meta integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    cod_filial integer NOT NULL,
    ano integer NOT NULL,
    mes integer NOT NULL CHECK (mes BETWEEN 1 AND 12),
    meta_quantidade numeric(14, 2) NOT NULL CHECK (meta_quantidade > 0),
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now(),
    UNIQUE (cod_empresa, cod_filial, ano, mes)
);

ALTER TABLE public.vendas_metas ENABLE ROW LEVEL SECURITY;

-- O submenu Metas abre com qualquer uma das duas. Nenhuma é concedida:
-- só o superusuário passa por bypass.
INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo)
SELECT v.sistema, v.opcao, v.descricao, v.ordem, TRUE
FROM (VALUES
    ('PERFORMANCES', 'METAS_CONSULTAR', 'Performance de Gerentes - Consultar Metas', 1190),
    ('PERFORMANCES', 'METAS_INFORMAR',  'Performance de Gerentes - Informar Metas', 1195)
) AS v(sistema, opcao, descricao, ordem)
WHERE NOT EXISTS (
    SELECT 1 FROM permissoes_catalogo p
    WHERE p.sistema = v.sistema AND p.opcao = v.opcao
);

-- Carga inicial: Metas_Rede_Lucena_Outubro_2026.xlsx (EMP010).
-- A planilha lista os 23 postos na mesma ordem do cadastro de filiais; três
-- nomes vieram grafados de outro jeito e foram casados pela posição:
-- "Zona Grande" = 4 Serra Grande, "Itaporimim" = 22 Ipaumirim,
-- "Campina Grande" = 23 Catingueira.
INSERT INTO vendas_metas (cod_empresa, cod_filial, ano, mes, meta_quantidade)
VALUES
    ('EMP010',  1, 2026, 10,  80000),
    ('EMP010',  2, 2026, 10,  20000),
    ('EMP010',  3, 2026, 10, 100000),
    ('EMP010',  4, 2026, 10,  47000),
    ('EMP010',  5, 2026, 10, 150000),
    ('EMP010',  6, 2026, 10,  58000),
    ('EMP010',  7, 2026, 10,  22000),
    ('EMP010',  8, 2026, 10,  87000),
    ('EMP010',  9, 2026, 10, 130000),
    ('EMP010', 10, 2026, 10, 180000),
    ('EMP010', 11, 2026, 10,  55000),
    ('EMP010', 12, 2026, 10, 160000),
    ('EMP010', 13, 2026, 10,  60000),
    ('EMP010', 14, 2026, 10, 150000),
    ('EMP010', 15, 2026, 10,  60000),
    ('EMP010', 16, 2026, 10, 240000),
    ('EMP010', 17, 2026, 10,  90000),
    ('EMP010', 18, 2026, 10,  85000),
    ('EMP010', 19, 2026, 10,  45000),
    ('EMP010', 20, 2026, 10,  40000),
    ('EMP010', 21, 2026, 10, 223000),
    ('EMP010', 22, 2026, 10, 300000),
    ('EMP010', 23, 2026, 10, 100000)
ON CONFLICT (cod_empresa, cod_filial, ano, mes) DO NOTHING;
