-- PDV Matrix — Canais de Venda.
--
-- Uma loja (filial) vende por mais de um canal: balcão, e-commerce, outlet.
-- Isso NÃO é filial: é a porta por onde a venda saiu. Tratar canal como
-- filial obrigaria a dividir o estoque entre eles, e na maior parte dos casos
-- o estoque é o mesmo — a peça está na loja e é anunciada também no site.
--
-- Daí o parâmetro `estoque_por_canal`:
--
--   FALSE (padrão) → os canais usam o estoque da filial. Existe um saldo só,
--                    e o canal serve para saber por onde a venda saiu.
--   TRUE           → cada canal tem saldo próprio, e mover peça de um canal
--                    para outro exige transferência.
--
-- O canal fica registrado no movimento de estoque e na venda dos dois jeitos:
-- mesmo com estoque compartilhado, dá para saber quanto o e-commerce vendeu.

CREATE TABLE IF NOT EXISTS public.pdv_canais_venda (
    id_pdv_canal integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    cod_filial integer NOT NULL,
    nome character varying NOT NULL,
    -- o canal padrão é o que a tela de venda já vem marcando
    padrao boolean NOT NULL DEFAULT FALSE,
    ativo boolean NOT NULL DEFAULT TRUE,
    ordem integer DEFAULT 10,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_canais_venda ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_canais_filial
    ON public.pdv_canais_venda (cod_empresa, cod_filial, ativo);

-- um canal padrão por filial
CREATE UNIQUE INDEX IF NOT EXISTS uq_pdv_canal_padrao
    ON public.pdv_canais_venda (cod_empresa, cod_filial)
    WHERE padrao;


-- Os canais usam o estoque da filial (FALSE) ou cada um tem o seu (TRUE)?
ALTER TABLE public.pdv_parametros
    ADD COLUMN IF NOT EXISTS estoque_por_canal boolean NOT NULL DEFAULT FALSE;


-- Por onde a peça entrou/saiu e por onde a venda saiu. Nulo = sem canal
-- definido (movimentos anteriores a este conceito).
ALTER TABLE public.pdv_estoque_movimentos
    ADD COLUMN IF NOT EXISTS id_pdv_canal integer
        REFERENCES public.pdv_canais_venda (id_pdv_canal);

ALTER TABLE public.pdv_vendas
    ADD COLUMN IF NOT EXISTS id_pdv_canal integer
        REFERENCES public.pdv_canais_venda (id_pdv_canal);

CREATE INDEX IF NOT EXISTS ix_pdv_estoque_mov_canal
    ON public.pdv_estoque_movimentos (cod_empresa, id_pdv_canal, id_pdv_produto);
CREATE INDEX IF NOT EXISTS ix_pdv_vendas_canal
    ON public.pdv_vendas (cod_empresa, id_pdv_canal, data_venda);


-- ─── CANAIS D'O CLOSET ───────────────────────────────────────────────────────
-- A EMP013 fica com a filial 1 e três canais nela, como no arquivo de estoque.

INSERT INTO public.pdv_canais_venda (cod_empresa, cod_filial, nome, padrao, ordem)
SELECT 'EMP013', 1, v.nome, v.padrao, v.ordem
FROM (VALUES
    ('Loja Física', TRUE,  10),
    ('E-commerce',  FALSE, 20),
    ('Outlet',      FALSE, 30)
) AS v(nome, padrao, ordem)
WHERE NOT EXISTS (
    SELECT 1 FROM public.pdv_canais_venda
    WHERE cod_empresa = 'EMP013' AND cod_filial = 1 AND nome = v.nome
);


INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo)
SELECT 'PDV', v.opcao, v.descricao, v.ordem, TRUE
FROM (VALUES
    ('CANAIS_VENDA',        'Configurar Canais de Venda',        1850),
    ('TRANSFERIR_ESTOQUE',  'Transferir Estoque entre Canais',   1860)
) AS v(opcao, descricao, ordem)
WHERE NOT EXISTS (
    SELECT 1 FROM permissoes_catalogo p
    WHERE p.sistema = 'PDV' AND p.opcao = v.opcao
);
