-- Módulo Mercado → ANP.
-- Base pública de postos revendedores publicada pela ANP, importada por CSV
-- (separador ';', UTF-8, cabeçalho CODIGOISIMP;AUTORIZACAO;DATAPUBLICACAO;
-- RAZAOSOCIAL;CNPJ;ENDERECO;COMPLEMENTO;BAIRRO;CEP;UF;MUNICIPIO;BANDEIRA;
-- DATAVINCULACAO).
--
-- EXCEÇÃO CONSCIENTE À CONVENÇÃO: estas tabelas NÃO têm `cod_empresa`. O dado é
-- público e nacional, idêntico para todas as empresas — replicá-lo por empresa
-- só multiplicaria 45 mil linhas iguais e faria cada uma importar o mesmo
-- arquivo. Quem vê e quem importa é decidido pela permissão
-- (MERCADO/CONSULTAR_ANP e MERCADO/IMPORTAR_CSV_ANP), não pelo tenant.
-- `mercado_anp_importacoes.cod_empresa_origem` guarda apenas de qual empresa o
-- usuário estava logado ao importar — é auditoria, não particionamento.
--
-- O arquivo é uma FOTOGRAFIA COMPLETA do país, não um incremental: cada
-- importação substitui a base inteira. Por isso não há merge por linha —
-- apaga e regrava dentro da mesma transação.
--
-- CNPJ e CODIGOISIMP vieram únicos no arquivo de 12/08/2026 (45.664 linhas,
-- zero repetição nos dois). A unicidade é garantida pelo CNPJ; CODIGOISIMP
-- fica só como referência da ANP.

CREATE TABLE IF NOT EXISTS public.mercado_anp_importacoes (
    id_anp_importacao  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_arquivo       character varying,
    data_arquivo       date,
    qtd_postos         integer      DEFAULT 0,
    id_usuario         integer,
    cod_empresa_origem character varying,
    criado_em          timestamp without time zone DEFAULT now(),
    atualizado_em      timestamp without time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mercado_anp_postos (
    id_anp_posto      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_anp_importacao integer REFERENCES public.mercado_anp_importacoes (id_anp_importacao),
    codigo_isimp      character varying,
    autorizacao       character varying,
    data_publicacao   date,
    razao_social      character varying,
    cnpj              character varying NOT NULL,
    endereco          character varying,
    complemento       character varying,
    bairro            character varying,
    cep               character varying,
    uf                character varying,
    municipio         character varying,
    bandeira          character varying,
    data_vinculacao   date,
    criado_em         timestamp without time zone DEFAULT now(),
    atualizado_em     timestamp without time zone DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_mercado_anp_postos_cnpj
    ON public.mercado_anp_postos (cnpj);

-- Índices das três totalizações da tela de consulta.
CREATE INDEX IF NOT EXISTS ix_mercado_anp_postos_uf
    ON public.mercado_anp_postos (uf);

CREATE INDEX IF NOT EXISTS ix_mercado_anp_postos_municipio
    ON public.mercado_anp_postos (uf, municipio);

CREATE INDEX IF NOT EXISTS ix_mercado_anp_postos_bandeira
    ON public.mercado_anp_postos (bandeira);

-- RLS: a aplicação usa a service role key (bypass). Sem isto a chave anônima,
-- que é pública, leria e apagaria a tabela pela API REST do Supabase.
ALTER TABLE public.mercado_anp_importacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mercado_anp_postos      ENABLE ROW LEVEL SECURITY;

-- Permissões das rotinas do módulo (o MENU 1500 vem em permissao_menu_mercado.sql).
INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo) VALUES
    ('MERCADO', 'IMPORTAR_CSV_ANP', 'Importar CSV ANP', 1501, true),
    ('MERCADO', 'CONSULTAR_ANP',    'Consultar ANP',    1502, true)
ON CONFLICT DO NOTHING;
