-- Projetos da Agenda (Canivete Suíço)
-- Por USUÁRIO, como o resto da agenda — não tem cod_empresa.
--
-- Cada projeto tem 3 blocos de tarefas:
--   metas        — repetição da programação do dia (texto + check)
--   recorrências — modelo mensal (cadastrado na engrenagem) + execuções do mês
--   eventuais    — tarefas avulsas (texto + check)

CREATE TABLE IF NOT EXISTS agenda_projetos (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario  integer NOT NULL,
    nome        text    NOT NULL,
    ordem       integer NOT NULL DEFAULT 10,
    ativo       boolean NOT NULL DEFAULT true,
    -- competência (1º dia do mês) das recorrências já carregadas
    competencia date,
    criado_em   timestamp without time zone DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_agenda_projetos_usuario
    ON agenda_projetos (id_usuario, ordem, id);

-- metas e eventuais moram na mesma tabela, separadas por bloco
CREATE TABLE IF NOT EXISTS agenda_proj_tarefas (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_projeto  integer NOT NULL REFERENCES agenda_projetos (id) ON DELETE CASCADE,
    bloco       character varying NOT NULL,   -- 'meta' | 'eventual'
    texto       text    NOT NULL DEFAULT '',
    concluido   boolean NOT NULL DEFAULT false,
    ordem       integer NOT NULL DEFAULT 10,
    criado_em   timestamp without time zone DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_agenda_proj_tarefas_projeto
    ON agenda_proj_tarefas (id_projeto, bloco, ordem, id);

-- modelo das recorrências mensais (o que repete todo mês)
CREATE TABLE IF NOT EXISTS agenda_proj_recorrencias (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_projeto  integer NOT NULL REFERENCES agenda_projetos (id) ON DELETE CASCADE,
    texto       text    NOT NULL DEFAULT '',
    ordem       integer NOT NULL DEFAULT 10,
    ativo       boolean NOT NULL DEFAULT true,
    criado_em   timestamp without time zone DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_agenda_proj_recorrencias_projeto
    ON agenda_proj_recorrencias (id_projeto, ordem, id);

-- execuções do mês: uma linha por recorrência por competência
CREATE TABLE IF NOT EXISTS agenda_proj_rec_execucoes (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_recorrencia integer NOT NULL REFERENCES agenda_proj_recorrencias (id) ON DELETE CASCADE,
    competencia    date    NOT NULL,          -- sempre o dia 1 do mês
    situacao       character varying NOT NULL DEFAULT 'pendente',  -- pendente|concluida|cancelada
    criado_em      timestamp without time zone DEFAULT now(),
    UNIQUE (id_recorrencia, competencia)
);
CREATE INDEX IF NOT EXISTS ix_agenda_proj_rec_exec_comp
    ON agenda_proj_rec_execucoes (competencia, situacao);
