-- O produto na loja: catálogo único, saldo e lista por filial.
--
-- `pdv_produtos` é o **cadastro central da empresa**: SKU, descrição, marca,
-- cor, tamanho, preço. A peça é a mesma em qualquer loja, e o SKU é único.
--
-- `pdv_produtos_filiais` diz **quais peças aquela loja trabalha** e quanto ela
-- tem de cada uma. Sem isso, uma loja pequena carregaria a lista inteira da
-- empresa — inclusive itens que ela nunca vendeu e que já estão obsoletos.
--
-- Como o item entra na loja:
--
--   * **sozinho**, quando aparece movimento dele ali (entrada, importação,
--     ajuste, transferência). Receber a mercadoria já inclui o item.
--   * **pelo SKU**, digitado na tela de estoque: copia o que precisa do
--     cadastro central e o item passa a existir naquela loja.
--
-- Como o item sai:
--
--   Ele **nunca é apagado** — venda e movimento apontam para ele, e o
--   histórico tem que continuar de pé. O que acontece é ficar `OCULTO`:
--   sai das listagens e da tela de venda, mas continua contando em qualquer
--   relatório de vendas passadas.
--
--   A ocultação é sugerida quando o item está **zerado e sem movimento há
--   MESES_SEM_MOVIMENTO** (6). Antes disso ele fica visível mesmo zerado,
--   porque zerar não quer dizer sair de linha: quer dizer repor.

CREATE TABLE IF NOT EXISTS public.pdv_produtos_filiais (
    id_pdv_produto_filial integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    cod_filial integer NOT NULL,
    id_pdv_produto integer NOT NULL REFERENCES public.pdv_produtos (id_pdv_produto),

    -- o saldo que vale é este: o da loja
    quantidade_atual numeric(14,3) NOT NULL DEFAULT 0,
    quantidade_reservada numeric(14,3) NOT NULL DEFAULT 0,
    -- mínimo e máximo são de cada loja: a matriz repõe diferente da filial
    estoque_minimo numeric(14,3) NOT NULL DEFAULT 0,
    estoque_maximo numeric(14,3) NOT NULL DEFAULT 0,

    -- ATIVO — aparece nas telas da loja
    -- OCULTO — sai das telas, mas continua no histórico
    situacao character varying NOT NULL DEFAULT 'ATIVO',

    incluido_em date NOT NULL DEFAULT CURRENT_DATE,
    -- como entrou: AUTOMATICA (veio movimento) ou MANUAL (digitaram o SKU)
    origem_inclusao character varying NOT NULL DEFAULT 'AUTOMATICA',
    -- data do último movimento — é ela que diz se a peça está parada
    ultimo_movimento_em date,
    ocultado_em date,

    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now(),

    CONSTRAINT uq_pdv_produto_filial UNIQUE (cod_empresa, cod_filial, id_pdv_produto)
);
ALTER TABLE public.pdv_produtos_filiais ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS ix_pdv_produtos_filiais_loja
    ON public.pdv_produtos_filiais (cod_empresa, cod_filial, situacao);
CREATE INDEX IF NOT EXISTS ix_pdv_produtos_filiais_produto
    ON public.pdv_produtos_filiais (id_pdv_produto);


-- ─── CARGA A PARTIR DO QUE JÁ EXISTE ─────────────────────────────────────────
-- O saldo por loja sai dos movimentos, que carregam cod_filial desde a fase 2.
-- Os valores por loja (reservado, mínimo, máximo) estavam no cadastro central
-- e descem para a filial que os movimentou.

INSERT INTO public.pdv_produtos_filiais
    (cod_empresa, cod_filial, id_pdv_produto, quantidade_atual,
     quantidade_reservada, estoque_minimo, estoque_maximo,
     origem_inclusao, incluido_em, ultimo_movimento_em)
SELECT m.cod_empresa, m.cod_filial, m.id_pdv_produto,
       SUM(m.quantidade),
       MAX(p.quantidade_reservada), MAX(p.estoque_minimo), MAX(p.estoque_maximo),
       'AUTOMATICA', MIN(m.data_movimento), MAX(m.data_movimento)
FROM public.pdv_estoque_movimentos m
JOIN public.pdv_produtos p ON p.id_pdv_produto = m.id_pdv_produto
GROUP BY m.cod_empresa, m.cod_filial, m.id_pdv_produto
ON CONFLICT (cod_empresa, cod_filial, id_pdv_produto) DO NOTHING;


-- ─── O CADASTRO CENTRAL PERDE O QUE É DA LOJA ────────────────────────────────
-- Saldo, reservado, mínimo e máximo passam a viver na filial. Manter cópia no
-- cadastro central seria total persistido em dois lugares — os dois divergem
-- na primeira falha, e aí ninguém sabe qual vale.

ALTER TABLE public.pdv_produtos
    DROP COLUMN IF EXISTS quantidade_atual,
    DROP COLUMN IF EXISTS quantidade_reservada,
    DROP COLUMN IF EXISTS estoque_minimo,
    DROP COLUMN IF EXISTS estoque_maximo;


INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo)
SELECT 'PDV', 'PRODUTOS_FILIAL', 'Incluir/ocultar produtos na loja', 1910, TRUE
WHERE NOT EXISTS (
    SELECT 1 FROM permissoes_catalogo
    WHERE sistema = 'PDV' AND opcao = 'PRODUTOS_FILIAL'
);
