-- Vistorias → Executar → Notas a Prazo: conferência do fiado do posto feita
-- na vistoria (planilha "CONFERÊNCIA GERAL"). Uma linha por cliente: soma das
-- notas físicas × valor no sistema, com observação. Prefeitura entra como
-- cliente. A diferença e os totais são calculados, nunca gravados.
--
-- composicao_* guarda o que foi digitado quando é uma soma ("309,40+278,60"),
-- como a fórmula da planilha — o valor é o resultado dela.
CREATE TABLE IF NOT EXISTS public.vistorias_notas_prazo (
    id_nota_prazo       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa         character varying NOT NULL,
    id_execucao         integer NOT NULL REFERENCES public.vistorias_execucoes (id_execucao) ON DELETE CASCADE,
    cliente             character varying NOT NULL,
    valor_notas         numeric(14,2) NOT NULL DEFAULT 0,
    composicao_notas    text,
    valor_sistema       numeric(14,2) NOT NULL DEFAULT 0,
    composicao_sistema  text,
    observacao          text,
    ordem               integer DEFAULT 10,
    criado_em           timestamp without time zone DEFAULT now(),
    atualizado_em       timestamp without time zone DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_vistorias_notas_prazo_execucao
    ON public.vistorias_notas_prazo (id_execucao, ordem);

ALTER TABLE public.vistorias_notas_prazo ENABLE ROW LEVEL SECURITY;
