-- =====================================================================
-- Saldos — importação dos valores de estoque vindos de Operações
--
-- Na tela de Saldos, as linhas de Compra de Combustível, Em Trânsito e
-- Estoque podem ser puxadas de Operações (mesmos números da Consulta de
-- Estoques, em R$) em vez de digitadas. Só é permitido quando a data está
-- bloqueada em Operações (operacoes_bloqueios).
--
-- `origem_estoque` marca QUAL indicador recebe cada valor — a tela não
-- adivinha por nome. Valores: COMPRA, TRANSITO, ESTOQUE. Indicador sem
-- marca nenhuma continua sendo só digitação manual.
--
-- Uma linha em saldos_importacoes_estoque = aquele indicador, naquela data
-- e área, veio de importação: os campos ficam travados e o botão vira
-- "Desfazer importação".
-- =====================================================================

ALTER TABLE indicadores_recebiveis
    ADD COLUMN IF NOT EXISTS origem_estoque character varying;

UPDATE indicadores_recebiveis SET origem_estoque = 'COMPRA'
 WHERE cod_empresa = 'EMP010' AND nome = 'Compra Combustível';

UPDATE indicadores_recebiveis SET origem_estoque = 'TRANSITO'
 WHERE cod_empresa = 'EMP010' AND nome = 'Em Trânsito';

UPDATE indicadores_recebiveis SET origem_estoque = 'ESTOQUE'
 WHERE cod_empresa = 'EMP010' AND nome = 'Estoque';

CREATE TABLE saldos_importacoes_estoque (
    id_importacao           integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa             character varying NOT NULL,
    data                    date NOT NULL,
    id_area                 integer NOT NULL,
    id_indicador_recebivel  integer NOT NULL,
    id_usuario              integer,
    criado_em               timestamp without time zone DEFAULT now(),
    CONSTRAINT uq_saldos_importacoes_estoque UNIQUE (cod_empresa, data, id_area, id_indicador_recebivel)
);

CREATE INDEX idx_saldos_importacoes_estoque_empresa_data
    ON saldos_importacoes_estoque (cod_empresa, data, id_area);

ALTER TABLE saldos_importacoes_estoque ENABLE ROW LEVEL SECURITY;

CREATE POLICY service_role_only ON saldos_importacoes_estoque FOR ALL TO service_role USING (true) WITH CHECK (true);
