-- Journal da Programação do Dia (Canivete Suíço → Agenda)
-- Mesmo desenho do journal dos projetos (agenda_proj_journal), mas a
-- Programação do Dia não é um projeto: a coluna é do próprio usuário,
-- então a chave aqui é id_usuario.
--
-- Edição/exclusão só no mesmo dia da criação, como no journal dos projetos.

CREATE TABLE IF NOT EXISTS agenda_dia_journal (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario    integer NOT NULL,
    data          date    NOT NULL,
    descricao     text    NOT NULL,
    criado_em     timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone
);

CREATE INDEX IF NOT EXISTS ix_agenda_dia_journal_usuario
    ON agenda_dia_journal (id_usuario, data DESC, id DESC);
