-- =====================================================================
-- Operações — liberação temporária de data para Informar Medições
--
-- O seletor de data de Informar Medições não é um calendário: ele oferece
-- hoje e, andando para trás, só enquanto o dia for domingo ou feriado
-- (`datas_medicao_permitidas`). Numa terça-feira, portanto, um feriado de
-- segunda já não aparece — e a medição daquele dia fica sem como ser
-- digitada.
--
-- Esta tabela abre uma data avulsa no seletor, temporariamente. Quem tem
-- OPERACOES/BLOQUEAR_MOVIMENTACOES libera; a liberação expira sozinha em
-- HORAS_LIBERACAO_MEDICOES horas, checada por horário na leitura, sem
-- rotina em background.
--
-- As liberações são ACUMULATIVAS: cada linha abre uma data, e todas as que
-- ainda não expiraram valem ao mesmo tempo. Ler só a última faria a
-- segunda liberação cancelar a primeira em silêncio (foi o bug de
-- caixas_liberacao_temporaria).
--
-- Ela NÃO fura o bloqueio de movimentações (`operacoes_bloqueios` nem o
-- automático de 10 dias): são duas regras independentes, e a gravação
-- continua checando `data_bloqueada`. Data bloqueada se reabre em
-- Operações → Bloquear Movimentações — a ativação aqui recusa, para a
-- verdade não ficar em dois lugares.
-- =====================================================================

CREATE TABLE public.operacoes_liberacao_temporaria (
    id_liberacao      integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa       character varying NOT NULL,
    data_liberada     date NOT NULL,
    ativado_em        timestamp without time zone NOT NULL DEFAULT now(),
    id_usuario_ativou integer REFERENCES public.usuarios (id_usuario),
    revogado_em       timestamp without time zone,
    criado_em         timestamp without time zone DEFAULT now()
);

CREATE INDEX idx_operacoes_liberacao_temporaria_empresa
    ON public.operacoes_liberacao_temporaria (cod_empresa, ativado_em DESC);

ALTER TABLE public.operacoes_liberacao_temporaria ENABLE ROW LEVEL SECURITY;
