-- Crédito — cadastro e análise de crédito de novo cliente (compras/abastecimentos
-- a prazo), a partir do formulário em papel "Cadastro e Análise de Crédito |
-- Novo Cliente" da Rede Lucena.
--
-- Uma linha por solicitação. O fluxo tem duas mãos:
--   1) o analista cadastra a solicitação e dá o parecer  -> status PENDENTE
--   2) quem tem alçada aprova/reprova com observação     -> status APROVADO /
--      APROVADO_COM_CONDICAO / REPROVADO
--
-- Nada de limite/prazo "efetivo" gravado em coluna derivada: a decisão manda,
-- e o que o analista recomendou fica registrado ao lado para comparação.

CREATE TABLE IF NOT EXISTS public.credito_analises (
    id_analise integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,

    -- 1. Identificação do cliente
    tipo_cliente character varying,                 -- PF | PJ
    nome_razao_social character varying,
    cpf_cnpj character varying,
    telefone character varying,
    cidade_uf character varying,
    profissao_atividade character varying,
    tempo_atividade character varying,
    responsavel_nome character varying,             -- só PJ
    responsavel_cpf character varying,

    -- 2. Crédito solicitado
    finalidade character varying,                   -- COMBUSTIVEL | LUBRIFICANTES | OUTROS
    finalidade_outros character varying,
    consumo_mensal_estimado numeric(14,2),
    limite_solicitado numeric(14,2),
    prazo_solicitado_dias integer,
    forma_cobranca character varying,

    -- 3. Capacidade financeira
    renda_faturamento numeric(14,2),
    endividamento numeric(14,2),
    documentacao_financeira character varying,      -- SIM | NAO | DISPENSADA

    -- 4. Consulta e risco de crédito
    biro_situacao character varying,                -- SEM_RESTRICAO | COM_RESTRICAO
    biro_score integer,
    protestos character varying,                    -- NAO | SIM
    protestos_valor numeric(14,2),
    situacao_documento character varying,           -- REGULAR | IRREGULAR
    referencia_comercial character varying,         -- FAVORAVEL | ATENCAO | NAO_NECESSARIA
    observacao_relevante text,

    -- 5. Parecer do setor de crédito (analista)
    classificacao_risco character varying,          -- BAIXO | MEDIO | ALTO
    parecer_credito character varying,              -- APROVAR | APROVAR_LIMITE_MENOR | APROVAR_CONDICAO | REPROVAR
    limite_recomendado numeric(14,2),
    prazo_recomendado_dias integer,
    justificativa text,

    id_usuario_analista integer,
    nome_analista character varying,
    data_analise date,

    -- Decisão final (aprovador)
    status character varying NOT NULL DEFAULT 'PENDENTE',  -- PENDENTE | APROVADO | APROVADO_COM_CONDICAO | REPROVADO
    limite_aprovado numeric(14,2),
    prazo_aprovado_dias integer,
    observacao_decisao text,
    id_usuario_aprovador integer,
    nome_aprovador character varying,
    data_decisao date,

    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_credito_analises_empresa_status
    ON public.credito_analises (cod_empresa, status);

ALTER TABLE public.credito_analises ENABLE ROW LEVEL SECURITY;


-- Permissões. Não concede a ninguém: só o superusuário passa por bypass.
-- Liberar em Usuários → Permissões.
INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo) VALUES
    ('FINANCEIRO', 'CREDITO_MENU',      'Crédito - Menu',                 1500, true),
    ('FINANCEIRO', 'CREDITO_CADASTRAR', 'Crédito - Cadastrar Análise',    1510, true),
    ('FINANCEIRO', 'CREDITO_APROVAR',   'Crédito - Aprovar Análise',      1520, true)
ON CONFLICT DO NOTHING;
