-- Quais empresas o usuário quer ver como ícone de atalho na barra do topo.
-- Preferência pessoal, não permissão: só entra aqui empresa que o usuário já
-- pode acessar (usuarios_empresas). Usuário sem nenhuma linha vê todas as suas
-- empresas na barra — é o padrão de quem nunca configurou nada.

CREATE TABLE IF NOT EXISTS public.usuarios_atalhos_empresas (
    id_usuarios_atalhos_empresas integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario integer NOT NULL REFERENCES public.usuarios (id_usuario),
    cod_empresa character varying NOT NULL,
    ordem integer NOT NULL DEFAULT 10,
    criado_em timestamp without time zone NOT NULL DEFAULT now(),
    atualizado_em timestamp without time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_usuarios_atalhos_empresas
    ON public.usuarios_atalhos_empresas (id_usuario, cod_empresa);

ALTER TABLE public.usuarios_atalhos_empresas ENABLE ROW LEVEL SECURITY;
