-- PDV Matrix — fase 2: estoque.
--
-- 1. Caixa padrão da loja: dinheiro não se escolhe conta.
-- 2. Movimentação de estoque — o "extrato bancário do produto".

-- ─── CAIXA PADRÃO ────────────────────────────────────────────────────────────
-- Na tela de venda, dinheiro é dinheiro: a vendedora não escolhe onde ele
-- cai, cai na gaveta. Mas todo lançamento financeiro precisa de uma conta
-- (é o extrato). Então a conta que representa a gaveta é marcada aqui, uma
-- vez, no cadastro, e o sistema resolve sozinho na hora da venda.
--
-- aceita_dinheiro/aceita_pix nasceram na fase 1 e nunca foram usadas — quem
-- decide isso agora é caixa_padrao. Saem para não ficar coluna morta.

ALTER TABLE public.pdv_contas_financeiras
    ADD COLUMN IF NOT EXISTS caixa_padrao boolean NOT NULL DEFAULT FALSE;

ALTER TABLE public.pdv_contas_financeiras DROP COLUMN IF EXISTS aceita_dinheiro;
ALTER TABLE public.pdv_contas_financeiras DROP COLUMN IF EXISTS aceita_pix;

-- Só uma conta por empresa pode ser a gaveta.
CREATE UNIQUE INDEX IF NOT EXISTS uq_pdv_caixa_padrao
    ON public.pdv_contas_financeiras (cod_empresa)
    WHERE caixa_padrao;


-- ─── MOVIMENTAÇÃO DE ESTOQUE ─────────────────────────────────────────────────
-- Funciona como o extrato de uma conta: entrada positiva, saída negativa.
-- Tudo o que entra ou sai do estoque gera uma linha aqui, e cada linha diz de
-- onde veio (venda, nota de entrada, ajuste, perda…), para dar
--
--     Saldo inicial + Entradas − Saídas = Saldo final
--
-- pdv_produtos.quantidade_atual é o consolidado desta tabela, atualizado na
-- mesma transação — nunca escrito por fora dela.

CREATE TABLE IF NOT EXISTS public.pdv_estoque_movimentos (
    id_pdv_estoque_movimento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    cod_filial integer NOT NULL,
    id_pdv_produto integer NOT NULL REFERENCES public.pdv_produtos (id_pdv_produto),
    data_movimento date NOT NULL,
    -- VENDA | ENTRADA | AJUSTE | DEVOLUCAO | PERDA | TRANSFERENCIA
    tipo character varying NOT NULL,
    quantidade numeric(14,3) NOT NULL,          -- entrada > 0, saída < 0
    custo_unitario numeric(14,4) NOT NULL DEFAULT 0,
    -- o documento que provocou o movimento: VENDA, NOTA_ENTRADA, AJUSTE…
    tipo_origem character varying NOT NULL DEFAULT 'AJUSTE',
    id_origem integer,
    historico character varying,
    id_usuario integer,
    criado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_estoque_movimentos ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS ix_pdv_estoque_mov_produto
    ON public.pdv_estoque_movimentos (cod_empresa, id_pdv_produto, data_movimento);
CREATE INDEX IF NOT EXISTS ix_pdv_estoque_mov_origem
    ON public.pdv_estoque_movimentos (cod_empresa, tipo_origem, id_origem);


-- ─── PERMISSÕES ──────────────────────────────────────────────────────────────

INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo)
SELECT 'PDV', v.opcao, v.descricao, v.ordem, TRUE
FROM (VALUES
    ('ESTOQUE',        'Consultar Estoque',            1720),
    ('AJUSTE_ESTOQUE', 'Ajustar Estoque (entrada/perda)', 1730)
) AS v(opcao, descricao, ordem)
WHERE NOT EXISTS (
    SELECT 1 FROM permissoes_catalogo p
    WHERE p.sistema = 'PDV' AND p.opcao = v.opcao
);
