-- PDV Matrix — fase 3: Entrada de Mercadorias.
--
--     CT-e / Frete
--       ↓
--     Nota Fiscal de Entrada → Itens da Nota
--       ↓
--     Custo do produto (mercadoria + frete rateado)
--       ↓
--     Estoque (entrada) + último preço de compra
--       ↓
--     Títulos a Pagar (parcelas com vencimento)
--
-- Separação que o documento exige: a Nota Fiscal representa a COMPRA; os
-- Títulos a Pagar representam as OBRIGAÇÕES dela. Uma nota de R$ 10.000 em 5x
-- continua sendo uma compra só, com cinco obrigações individualizadas. E a
-- entrada da mercadoria NÃO é o pagamento dela: o lançamento no fluxo de caixa
-- só nasce quando o título for efetivamente pago.

-- ─── FORNECEDORES ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.pdv_fornecedores (
    id_pdv_fornecedor integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    nome character varying NOT NULL,
    cnpj character varying,
    telefone character varying,
    email character varying,
    endereco character varying,
    observacao text,
    ativo boolean NOT NULL DEFAULT TRUE,
    ordem integer DEFAULT 10,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_fornecedores ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_fornecedores_empresa ON public.pdv_fornecedores (cod_empresa, ativo);


-- ─── CT-e (FRETE) ────────────────────────────────────────────────────────────
-- Registrado ANTES da nota fiscal, de propósito: durante o lançamento da nota
-- é preciso poder vincular o CT-e à compra, porque o frete faz parte do custo
-- da mercadoria.

CREATE TABLE IF NOT EXISTS public.pdv_ctes (
    id_pdv_cte integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    numero character varying,
    serie character varying,
    chave character varying,
    transportadora character varying NOT NULL,
    data_emissao date,
    valor_total numeric(14,2) NOT NULL DEFAULT 0,
    observacao text,
    ativo boolean NOT NULL DEFAULT TRUE,
    ordem integer DEFAULT 10,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_ctes ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_ctes_empresa ON public.pdv_ctes (cod_empresa, ativo);


-- ─── NOTA FISCAL DE ENTRADA ──────────────────────────────────────────────────
-- Cabeçalho da compra. Nunca misturado com os itens.

CREATE TABLE IF NOT EXISTS public.pdv_notas_entrada (
    id_pdv_nota_entrada integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    cod_filial integer NOT NULL,
    id_pdv_fornecedor integer REFERENCES public.pdv_fornecedores (id_pdv_fornecedor),
    nome_fornecedor character varying,
    numero character varying NOT NULL,
    serie character varying,
    chave_nfe character varying,
    data_emissao date,
    data_entrada date NOT NULL,
    -- o CT-e vinculado: o frete dele entra no custo dos itens
    id_pdv_cte integer REFERENCES public.pdv_ctes (id_pdv_cte),
    valor_produtos numeric(14,2) NOT NULL DEFAULT 0,
    valor_desconto numeric(14,2) NOT NULL DEFAULT 0,
    valor_frete numeric(14,2) NOT NULL DEFAULT 0,
    valor_total numeric(14,2) NOT NULL DEFAULT 0,
    condicao_pagamento character varying,
    situacao character varying NOT NULL DEFAULT 'CONCLUIDA',   -- CONCLUIDA | CANCELADA
    observacao text,
    id_usuario integer,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_notas_entrada ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_notas_entrada_data
    ON public.pdv_notas_entrada (cod_empresa, data_entrada);
CREATE INDEX IF NOT EXISTS ix_pdv_notas_entrada_fornecedor
    ON public.pdv_notas_entrada (cod_empresa, id_pdv_fornecedor);


CREATE TABLE IF NOT EXISTS public.pdv_notas_entrada_itens (
    id_pdv_nota_entrada_item integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    id_pdv_nota_entrada integer NOT NULL
        REFERENCES public.pdv_notas_entrada (id_pdv_nota_entrada) ON DELETE CASCADE,
    sequencia integer NOT NULL DEFAULT 1,
    id_pdv_produto integer REFERENCES public.pdv_produtos (id_pdv_produto),
    descricao_produto character varying NOT NULL,
    unidade character varying NOT NULL DEFAULT 'UN',
    quantidade numeric(14,3) NOT NULL DEFAULT 0,
    preco_unitario numeric(14,4) NOT NULL DEFAULT 0,
    valor_desconto numeric(14,2) NOT NULL DEFAULT 0,
    valor_total numeric(14,2) NOT NULL DEFAULT 0,
    -- parcela do frete que coube a este item (rateio proporcional ao valor)
    valor_frete_rateado numeric(14,2) NOT NULL DEFAULT 0,
    -- (valor do item + frete rateado) / quantidade — é este que vai ao estoque
    custo_unitario numeric(14,4) NOT NULL DEFAULT 0,
    criado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_notas_entrada_itens ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_notas_entrada_itens_nota
    ON public.pdv_notas_entrada_itens (id_pdv_nota_entrada);


-- ─── TÍTULOS A PAGAR ─────────────────────────────────────────────────────────
-- A obrigação financeira, separada do documento que a originou. Espelho de
-- pdv_titulos_receber.

CREATE TABLE IF NOT EXISTS public.pdv_titulos_pagar (
    id_pdv_titulo_pagar integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    id_pdv_nota_entrada integer REFERENCES public.pdv_notas_entrada (id_pdv_nota_entrada),
    id_pdv_fornecedor integer REFERENCES public.pdv_fornecedores (id_pdv_fornecedor),
    nome_fornecedor character varying,
    numero_parcela integer NOT NULL DEFAULT 1,
    total_parcelas integer NOT NULL DEFAULT 1,
    valor numeric(14,2) NOT NULL DEFAULT 0,
    valor_baixado numeric(14,2) NOT NULL DEFAULT 0,
    data_vencimento date NOT NULL,
    documento character varying,
    situacao character varying NOT NULL DEFAULT 'ABERTO',   -- ABERTO | BAIXADO
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_titulos_pagar ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_titulos_pagar_situacao
    ON public.pdv_titulos_pagar (cod_empresa, situacao, data_vencimento);


-- ─── PERMISSÕES ──────────────────────────────────────────────────────────────

INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo)
SELECT 'PDV', v.opcao, v.descricao, v.ordem, TRUE
FROM (VALUES
    ('FORNECEDORES',        'Cadastro de Fornecedores',      1740),
    ('CTE',                 'Cadastro de CT-e / Fretes',     1750),
    ('ENTRADA_MERCADORIAS', 'Entrada de Mercadorias',        1760),
    ('CONTAS_PAGAR',        'Consultar Contas a Pagar',      1770)
) AS v(opcao, descricao, ordem)
WHERE NOT EXISTS (
    SELECT 1 FROM permissoes_catalogo p
    WHERE p.sistema = 'PDV' AND p.opcao = v.opcao
);
