-- =====================================================================
-- Módulo Saldos (Matrix / Financeiro) — acesso por área
-- Permite ao superusuário/admin conceder a um usuário acesso a uma ou mais
-- áreas dentro da tela de Saldos (ex.: Thalyta só acessa Área I, Carol só
-- acessa Área II). Basta ter a área concedida aqui para ver/lançar em todas
-- as filiais daquela área nesta tela — não depende de usuarios_filiais.
-- =====================================================================

CREATE TABLE usuarios_areas_saldos (
    id_usuario_area_saldo  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa            character varying NOT NULL,
    id_usuario             integer NOT NULL REFERENCES usuarios (id_usuario),
    id_area                integer NOT NULL REFERENCES areas (id_area),
    ativo                  boolean NOT NULL DEFAULT true,
    criado_em              timestamp without time zone DEFAULT now(),
    atualizado_em          timestamp without time zone DEFAULT now(),
    UNIQUE (cod_empresa, id_usuario, id_area)
);

CREATE INDEX idx_usuarios_areas_saldos_usuario ON usuarios_areas_saldos (cod_empresa, id_usuario);

ALTER TABLE usuarios_areas_saldos ENABLE ROW LEVEL SECURITY;

CREATE POLICY service_role_only ON usuarios_areas_saldos FOR ALL TO service_role USING (true) WITH CHECK (true);
