-- PDV Matrix — fase 6: Devolução e Cancelamento de Venda.
--
-- Isto não está no documento da Inovai, mas segue o princípio dele: **a venda
-- registra e encerra a operação comercial**. Devolver não é reabrir a venda —
-- é uma OPERAÇÃO NOVA, com documento próprio, que aponta para a venda de
-- origem e produz os efeitos contrários nos módulos:
--
--     Devolução → Itens devolvidos → volta ao Estoque
--               → destino do valor  → Caixa / Nota a Prazo / Estorno de cartão
--
-- A venda original continua com seus itens, seus valores e suas formas de
-- recebimento intactos. O único campo dela que muda é `situacao`, e só quando
-- a devolução é total: é um marcador de estado, não uma alteração de valores.
-- Quem quiser saber o que foi devolvido lê o documento de devolução.
--
-- Cancelamento é a devolução total: mesma tabela, mesmo caminho. Não existe
-- "apagar a venda" — o histórico do dia tem que continuar de pé.

CREATE TABLE IF NOT EXISTS public.pdv_devolucoes (
    id_pdv_devolucao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    cod_filial integer NOT NULL,
    numero_devolucao integer NOT NULL,
    id_pdv_venda integer NOT NULL REFERENCES public.pdv_vendas (id_pdv_venda),
    data_devolucao date NOT NULL,
    -- TOTAL (cancelamento) | PARCIAL
    tipo character varying NOT NULL DEFAULT 'PARCIAL',
    -- para onde vai o valor devolvido:
    --   DINHEIRO               → sai da conta financeira (lança negativo)
    --   ABATIMENTO_NOTA_PRAZO  → abate a nota a prazo em aberto (não é dinheiro)
    --   ESTORNO_CARTAO         → estorno pela operadora (não passa pelo caixa)
    destino_valor character varying NOT NULL DEFAULT 'DINHEIRO',
    id_pdv_conta_financeira integer
        REFERENCES public.pdv_contas_financeiras (id_pdv_conta_financeira),
    valor_total numeric(14,2) NOT NULL DEFAULT 0,
    motivo character varying,
    id_usuario integer,
    nome_usuario character varying,
    criado_em timestamp without time zone DEFAULT now(),
    CONSTRAINT uq_pdv_devolucoes_numero UNIQUE (cod_empresa, cod_filial, numero_devolucao)
);
ALTER TABLE public.pdv_devolucoes ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_devolucoes_venda
    ON public.pdv_devolucoes (cod_empresa, id_pdv_venda);
CREATE INDEX IF NOT EXISTS ix_pdv_devolucoes_data
    ON public.pdv_devolucoes (cod_empresa, data_devolucao);


CREATE TABLE IF NOT EXISTS public.pdv_devolucoes_itens (
    id_pdv_devolucao_item integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    id_pdv_devolucao integer NOT NULL
        REFERENCES public.pdv_devolucoes (id_pdv_devolucao) ON DELETE CASCADE,
    -- o item da venda que está voltando: é isto que impede devolver mais do
    -- que foi vendido
    id_pdv_venda_item integer NOT NULL
        REFERENCES public.pdv_vendas_itens (id_pdv_venda_item),
    id_pdv_produto integer REFERENCES public.pdv_produtos (id_pdv_produto),
    descricao_produto character varying NOT NULL,
    unidade character varying NOT NULL DEFAULT 'UN',
    quantidade numeric(14,3) NOT NULL DEFAULT 0,
    preco_unitario numeric(14,2) NOT NULL DEFAULT 0,
    valor_total numeric(14,2) NOT NULL DEFAULT 0,
    custo_unitario numeric(14,4) NOT NULL DEFAULT 0,
    criado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_devolucoes_itens ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_devolucoes_itens_devolucao
    ON public.pdv_devolucoes_itens (id_pdv_devolucao);
CREATE INDEX IF NOT EXISTS ix_pdv_devolucoes_itens_venda_item
    ON public.pdv_devolucoes_itens (id_pdv_venda_item);


INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo)
SELECT 'PDV', 'DEVOLUCOES', 'Devolução e Cancelamento de Venda', 1840, TRUE
WHERE NOT EXISTS (
    SELECT 1 FROM permissoes_catalogo
    WHERE sistema = 'PDV' AND opcao = 'DEVOLUCOES'
);
