-- =====================================================================
-- Módulo RH — cadastro livre de descrição de funções
-- Independente de funcionarios/cargos: só título + texto livre, para
-- documentar o que cada função/atribuição envolve (colado de um texto
-- já pronto). Sem vínculo com funcionário ou cargo específico.
-- =====================================================================

CREATE TABLE rh_funcoes (
    id             integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa    character varying NOT NULL,
    titulo         character varying NOT NULL,
    descricao      text NOT NULL,
    ativo          boolean NOT NULL DEFAULT true,
    criado_em      timestamp without time zone DEFAULT now(),
    atualizado_em  timestamp without time zone DEFAULT now()
);

CREATE INDEX idx_rh_funcoes_empresa ON rh_funcoes (cod_empresa, ativo);

ALTER TABLE rh_funcoes ENABLE ROW LEVEL SECURITY;

CREATE POLICY service_role_only ON rh_funcoes FOR ALL TO service_role USING (true) WITH CHECK (true);

INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo) VALUES
    ('RH', 'FUNCOES',            'Cadastro de Funções', 1070, true),
    ('RH', 'CONSULTAR_FUNCOES',  'Consultar Funções',   1080, true);
