-- Journal por projeto da Agenda (Canivete Suíço)
-- Equivalente ao Project Journal de Projetos, mas por USUÁRIO:
-- pendura no projeto da agenda, que já é do usuário — nada de cod_empresa.
--
-- Edição/exclusão só no mesmo dia da criação, igual ao Project Journal.

CREATE TABLE IF NOT EXISTS agenda_proj_journal (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_projeto    integer NOT NULL REFERENCES agenda_projetos (id) ON DELETE CASCADE,
    data          date    NOT NULL,
    descricao     text    NOT NULL,
    criado_em     timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone
);

CREATE INDEX IF NOT EXISTS ix_agenda_proj_journal_projeto
    ON agenda_proj_journal (id_projeto, data DESC, id DESC);
