-- =====================================================================
-- Módulo Saldos (Matrix / Financeiro) — feriados
-- A tela de Saldos só trabalha com dias úteis: sábados, domingos e os
-- feriados cadastrados aqui não geram bloco de dia, e a variação encosta
-- um dia útil no dia útil anterior (ex.: sexta → segunda).
-- Cadastro por empresa, igual a contas_bancarias/indicadores_recebiveis.
-- =====================================================================

CREATE TABLE saldos_feriados (
    id_feriado     integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa    character varying NOT NULL,
    data           date NOT NULL,
    descricao      character varying,
    criado_em      timestamp without time zone DEFAULT now(),
    atualizado_em  timestamp without time zone DEFAULT now(),
    CONSTRAINT uq_saldos_feriados_empresa_data UNIQUE (cod_empresa, data)
);

CREATE INDEX idx_saldos_feriados_empresa_data ON saldos_feriados (cod_empresa, data);

ALTER TABLE saldos_feriados ENABLE ROW LEVEL SECURITY;

CREATE POLICY service_role_only ON saldos_feriados FOR ALL TO service_role USING (true) WITH CHECK (true);
