-- CR → Fiado → Recebimentos por Dia
--
-- Quanto cada filial recebeu, dia a dia, do relatório de Notas/Duplicatas a
-- Receber (WebPostos). Uma linha por (empresa, filial, data): o valor é a soma
-- da coluna "Pago (R$)" das duplicatas cuja data de pagamento é aquele dia —
-- é esse número que fecha com os subtotais do próprio relatório.
--
-- Totais por dia, por filial e geral são calculados na consulta, nunca
-- persistidos. A filial é referenciada por (cod_empresa, cod_filial); o nome
-- do arquivo é resolvido por filiais.nome_filial_importacao, como nas demais
-- importações do WebPostos.

CREATE TABLE IF NOT EXISTS public.cr_recebimentos_dia (
    id_recebimento    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa       character varying NOT NULL,
    cod_filial        integer NOT NULL,
    data              date NOT NULL,
    valor             numeric(14,2) NOT NULL DEFAULT 0,
    quantidade        integer NOT NULL DEFAULT 0,
    nome_arquivo      character varying,
    criado_em         timestamp without time zone DEFAULT now(),
    atualizado_em     timestamp without time zone DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_cr_recebimentos_dia
    ON public.cr_recebimentos_dia (cod_empresa, cod_filial, data);

CREATE INDEX IF NOT EXISTS ix_cr_recebimentos_dia_periodo
    ON public.cr_recebimentos_dia (cod_empresa, data);

ALTER TABLE public.cr_recebimentos_dia ENABLE ROW LEVEL SECURITY;

INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo) VALUES
    ('FINANCEIRO', 'RECEBIMENTOS_DIA',      'CR — Recebimentos por Dia',            2100, true),
    ('FINANCEIRO', 'RECEBIMENTOS_IMPORTAR', 'CR — Importar Recebimentos por Dia',   2110, true)
ON CONFLICT DO NOTHING;
