-- PDV Matrix — fase 1: cadastros, venda (venda/itens/recebimentos) e os
-- destinos de cada forma de recebimento.
--
-- Arquitetura conforme "ESTRUTURA DO FINANCEIRO PARA SISTEMAS DE GESTÃO
-- INFORMATIZADOS" (Inovai, 16/08/2026): a venda registra e encerra a operação
-- comercial; tudo que acontece depois (baixa de nota a prazo, crédito de
-- cartão, conciliação de maleta) pertence aos módulos de destino e NUNCA
-- altera a venda original.
--
-- Nenhuma tabela do Matrix existente é tocada. O PDV tem o seu próprio núcleo
-- financeiro (pdv_contas_financeiras + pdv_lancamentos_financeiros), usado
-- hoje só pela INOVAI (EMP001).
--
-- Rodar uma vez. Todas as tabelas nascem com RLS habilitado e sem policy: a
-- aplicação usa a service role key (bypass) e a chave anônima é pública.

-- O PDV roda em EMP013 (O Closet), que já tem a filial 1 ("Loja 1"). Toda
-- tabela aqui referencia filial por (cod_empresa, cod_filial), no padrão do
-- sistema — a empresa que for operar com PDV precisa ter pelo menos uma.


-- ─── CADASTROS ───────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.pdv_clientes (
    id_pdv_cliente integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    nome character varying NOT NULL,
    cpf_cnpj character varying,
    telefone character varying,
    email character varying,
    endereco character varying,
    limite_credito numeric(14,2) NOT NULL DEFAULT 0,
    observacao text,
    ativo boolean NOT NULL DEFAULT TRUE,
    ordem integer DEFAULT 10,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_clientes ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_clientes_empresa ON public.pdv_clientes (cod_empresa, ativo);


-- Vendedor é cadastro próprio: quem vende não é necessariamente usuário do
-- Matrix. id_usuario, quando preenchido, amarra o vendedor ao login.
CREATE TABLE IF NOT EXISTS public.pdv_vendedores (
    id_pdv_vendedor integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    nome character varying NOT NULL,
    apelido character varying,
    id_usuario integer,
    ativo boolean NOT NULL DEFAULT TRUE,
    ordem integer DEFAULT 10,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_vendedores ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_vendedores_empresa ON public.pdv_vendedores (cod_empresa, ativo);


-- Cadastro/saldo do item de estoque. quantidade_atual e custo_atual são o
-- consolidado; a movimentação (o "extrato do produto") entra na fase 2.
CREATE TABLE IF NOT EXISTS public.pdv_produtos (
    id_pdv_produto integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    codigo character varying,
    descricao character varying NOT NULL,
    unidade character varying NOT NULL DEFAULT 'UN',
    preco_venda numeric(14,2) NOT NULL DEFAULT 0,
    custo_atual numeric(14,4) NOT NULL DEFAULT 0,
    ultimo_preco_compra numeric(14,4) NOT NULL DEFAULT 0,
    quantidade_atual numeric(14,3) NOT NULL DEFAULT 0,
    ativo boolean NOT NULL DEFAULT TRUE,
    ordem integer DEFAULT 10,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_produtos ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_produtos_empresa ON public.pdv_produtos (cod_empresa, ativo);
CREATE INDEX IF NOT EXISTS ix_pdv_produtos_codigo ON public.pdv_produtos (cod_empresa, codigo);


-- Conta financeira = qualquer lugar onde o dinheiro da empresa possa ficar,
-- ainda que temporariamente. O "Caixa da Eduarda" é uma conta como o Itaú.
CREATE TABLE IF NOT EXISTS public.pdv_contas_financeiras (
    id_pdv_conta_financeira integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    nome character varying NOT NULL,
    tipo character varying NOT NULL DEFAULT 'CAIXA',   -- CAIXA | BANCO
    banco character varying,
    agencia character varying,
    conta character varying,
    saldo_inicial numeric(14,2) NOT NULL DEFAULT 0,
    data_saldo_inicial date,
    aceita_dinheiro boolean NOT NULL DEFAULT TRUE,
    aceita_pix boolean NOT NULL DEFAULT TRUE,
    ativo boolean NOT NULL DEFAULT TRUE,
    ordem integer DEFAULT 10,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_contas_financeiras ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_contas_financeiras_empresa ON public.pdv_contas_financeiras (cod_empresa, ativo);


CREATE TABLE IF NOT EXISTS public.pdv_operadoras_cartao (
    id_pdv_operadora integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    nome character varying NOT NULL,
    aceita_debito boolean NOT NULL DEFAULT TRUE,
    aceita_credito boolean NOT NULL DEFAULT TRUE,
    dias_credito_debito integer NOT NULL DEFAULT 1,
    dias_credito_credito integer NOT NULL DEFAULT 30,
    ativo boolean NOT NULL DEFAULT TRUE,
    ordem integer DEFAULT 10,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_operadoras_cartao ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_operadoras_empresa ON public.pdv_operadoras_cartao (cod_empresa, ativo);


-- ─── NÚCLEO FINANCEIRO ───────────────────────────────────────────────────────
-- Extrato da empresa: entradas positivas, saídas negativas. Só dinheiro que
-- efetivamente se movimentou. Título a receber NÃO é lançamento.

CREATE TABLE IF NOT EXISTS public.pdv_lancamentos_financeiros (
    id_pdv_lancamento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    id_pdv_conta_financeira integer NOT NULL
        REFERENCES public.pdv_contas_financeiras (id_pdv_conta_financeira),
    data_lancamento date NOT NULL,
    valor numeric(14,2) NOT NULL,          -- entrada > 0, saída < 0
    historico character varying NOT NULL,
    -- de onde veio: VENDA, NOTA_PRAZO, TITULO, TRANSFERENCIA, MANUAL, ...
    tipo_origem character varying NOT NULL DEFAULT 'MANUAL',
    id_origem integer,
    -- as duas pernas de uma transferência compartilham o mesmo par
    id_transferencia integer,
    conciliado boolean NOT NULL DEFAULT FALSE,
    id_usuario integer,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_lancamentos_financeiros ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_lancamentos_conta_data
    ON public.pdv_lancamentos_financeiros (cod_empresa, id_pdv_conta_financeira, data_lancamento);
CREATE INDEX IF NOT EXISTS ix_pdv_lancamentos_origem
    ON public.pdv_lancamentos_financeiros (cod_empresa, tipo_origem, id_origem);


-- ─── VENDA ───────────────────────────────────────────────────────────────────
-- Cabeçalho (sintético). Uma linha por venda. Concluída, não volta a ser
-- alterada.

CREATE TABLE IF NOT EXISTS public.pdv_vendas (
    id_pdv_venda integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    cod_filial integer NOT NULL,
    numero_venda integer NOT NULL,
    data_venda date NOT NULL,
    hora_venda time without time zone NOT NULL DEFAULT now(),
    id_pdv_cliente integer REFERENCES public.pdv_clientes (id_pdv_cliente),
    nome_cliente character varying,
    id_pdv_vendedor integer REFERENCES public.pdv_vendedores (id_pdv_vendedor),
    nome_vendedor character varying,
    valor_bruto numeric(14,2) NOT NULL DEFAULT 0,
    valor_desconto numeric(14,2) NOT NULL DEFAULT 0,
    valor_total numeric(14,2) NOT NULL DEFAULT 0,
    situacao character varying NOT NULL DEFAULT 'CONCLUIDA',  -- CONCLUIDA | CANCELADA
    observacao text,
    id_usuario integer,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now(),
    CONSTRAINT uq_pdv_vendas_numero UNIQUE (cod_empresa, cod_filial, numero_venda)
);
ALTER TABLE public.pdv_vendas ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_vendas_data ON public.pdv_vendas (cod_empresa, data_venda);
CREATE INDEX IF NOT EXISTS ix_pdv_vendas_cliente ON public.pdv_vendas (cod_empresa, id_pdv_cliente);


CREATE TABLE IF NOT EXISTS public.pdv_vendas_itens (
    id_pdv_venda_item integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    id_pdv_venda integer NOT NULL REFERENCES public.pdv_vendas (id_pdv_venda) ON DELETE CASCADE,
    sequencia integer NOT NULL DEFAULT 1,
    id_pdv_produto integer REFERENCES public.pdv_produtos (id_pdv_produto),
    descricao_produto character varying NOT NULL,
    unidade character varying NOT NULL DEFAULT 'UN',
    quantidade numeric(14,3) NOT NULL DEFAULT 0,
    preco_unitario numeric(14,2) NOT NULL DEFAULT 0,
    valor_desconto numeric(14,2) NOT NULL DEFAULT 0,
    valor_total numeric(14,2) NOT NULL DEFAULT 0,
    custo_unitario numeric(14,4) NOT NULL DEFAULT 0,
    criado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_vendas_itens ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_vendas_itens_venda ON public.pdv_vendas_itens (id_pdv_venda);


-- Formas de recebimento são registros independentes — nada de valor_dinheiro,
-- valor_pix, valor_cartao como colunas da venda. Uma forma nova não muda o
-- schema da venda.
CREATE TABLE IF NOT EXISTS public.pdv_vendas_recebimentos (
    id_pdv_venda_recebimento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    id_pdv_venda integer NOT NULL REFERENCES public.pdv_vendas (id_pdv_venda) ON DELETE CASCADE,
    sequencia integer NOT NULL DEFAULT 1,
    -- DINHEIRO | PIX | DEBITO | CREDITO | NOTA_PRAZO | CONSIGNACAO
    forma character varying NOT NULL,
    valor numeric(14,2) NOT NULL DEFAULT 0,
    -- dinheiro/PIX: conta que recebeu o dinheiro
    id_pdv_conta_financeira integer REFERENCES public.pdv_contas_financeiras (id_pdv_conta_financeira),
    -- cartão: operadora e parcelas (corrigíveis depois no Caixa Central)
    id_pdv_operadora integer REFERENCES public.pdv_operadoras_cartao (id_pdv_operadora),
    qtd_parcelas integer NOT NULL DEFAULT 1,
    nsu character varying,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_vendas_recebimentos ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_vendas_receb_venda ON public.pdv_vendas_recebimentos (id_pdv_venda);
CREATE INDEX IF NOT EXISTS ix_pdv_vendas_receb_forma ON public.pdv_vendas_recebimentos (cod_empresa, forma);


-- ─── DESTINOS DE CADA FORMA DE RECEBIMENTO ───────────────────────────────────
-- DINHEIRO e PIX → pdv_lancamentos_financeiros (acima), direto no caixa.

-- Nota a prazo: pendência financeira do cliente. Nasce da venda e vive no
-- Financeiro. Pode ser baixada direto ou convertida em títulos.
CREATE TABLE IF NOT EXISTS public.pdv_notas_prazo (
    id_pdv_nota_prazo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    cod_filial integer NOT NULL,
    id_pdv_venda integer NOT NULL REFERENCES public.pdv_vendas (id_pdv_venda),
    id_pdv_venda_recebimento integer REFERENCES public.pdv_vendas_recebimentos (id_pdv_venda_recebimento),
    id_pdv_cliente integer REFERENCES public.pdv_clientes (id_pdv_cliente),
    nome_cliente character varying,
    id_pdv_vendedor integer REFERENCES public.pdv_vendedores (id_pdv_vendedor),
    data_emissao date NOT NULL,
    valor numeric(14,2) NOT NULL DEFAULT 0,
    valor_baixado numeric(14,2) NOT NULL DEFAULT 0,
    -- ABERTA | BAIXADA | CONVERTIDA
    situacao character varying NOT NULL DEFAULT 'ABERTA',
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_notas_prazo ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_notas_prazo_situacao ON public.pdv_notas_prazo (cod_empresa, situacao);
CREATE INDEX IF NOT EXISTS ix_pdv_notas_prazo_cliente ON public.pdv_notas_prazo (cod_empresa, id_pdv_cliente);


-- Título a receber: parcela formalizada, com vencimento. Vem de uma nota a
-- prazo — a rastreabilidade título → nota → venda → vendedor tem que existir.
CREATE TABLE IF NOT EXISTS public.pdv_titulos_receber (
    id_pdv_titulo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    id_pdv_nota_prazo integer REFERENCES public.pdv_notas_prazo (id_pdv_nota_prazo),
    id_pdv_cliente integer REFERENCES public.pdv_clientes (id_pdv_cliente),
    numero_parcela integer NOT NULL DEFAULT 1,
    total_parcelas integer NOT NULL DEFAULT 1,
    valor numeric(14,2) NOT NULL DEFAULT 0,
    valor_baixado numeric(14,2) NOT NULL DEFAULT 0,
    data_vencimento date NOT NULL,
    documento character varying,
    -- ABERTO | BAIXADO
    situacao character varying NOT NULL DEFAULT 'ABERTO',
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_titulos_receber ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_titulos_situacao ON public.pdv_titulos_receber (cod_empresa, situacao, data_vencimento);


-- Cartão: a operação (uma linha por recebimento de cartão da venda) …
CREATE TABLE IF NOT EXISTS public.pdv_cartoes_recebimentos (
    id_pdv_cartao_recebimento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    cod_filial integer NOT NULL,
    id_pdv_venda integer NOT NULL REFERENCES public.pdv_vendas (id_pdv_venda),
    id_pdv_venda_recebimento integer REFERENCES public.pdv_vendas_recebimentos (id_pdv_venda_recebimento),
    id_pdv_operadora integer REFERENCES public.pdv_operadoras_cartao (id_pdv_operadora),
    modalidade character varying NOT NULL,           -- DEBITO | CREDITO
    data_venda date NOT NULL,
    valor_bruto numeric(14,2) NOT NULL DEFAULT 0,
    qtd_parcelas integer NOT NULL DEFAULT 1,
    nsu character varying,
    situacao character varying NOT NULL DEFAULT 'ABERTO',
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_cartoes_recebimentos ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_cartoes_receb_data ON public.pdv_cartoes_recebimentos (cod_empresa, data_venda);

-- … e o detalhe. Débito gera uma linha; crédito em 6x gera seis. O detalhe
-- existe mesmo quando a empresa antecipa os recebíveis: é ele que responde
-- "como essa venda foi feita" numa auditoria.
CREATE TABLE IF NOT EXISTS public.pdv_cartoes_parcelas (
    id_pdv_cartao_parcela integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    id_pdv_cartao_recebimento integer NOT NULL
        REFERENCES public.pdv_cartoes_recebimentos (id_pdv_cartao_recebimento) ON DELETE CASCADE,
    numero_parcela integer NOT NULL DEFAULT 1,
    valor numeric(14,2) NOT NULL DEFAULT 0,
    previsao_credito date,
    situacao character varying NOT NULL DEFAULT 'A_RECEBER',   -- A_RECEBER | RECEBIDO
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_cartoes_parcelas ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_cartoes_parcelas_receb ON public.pdv_cartoes_parcelas (id_pdv_cartao_recebimento);


-- Consignação = envio das maletas. Tratamento próprio, de conciliação.
CREATE TABLE IF NOT EXISTS public.pdv_consignacoes (
    id_pdv_consignacao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    cod_filial integer NOT NULL,
    id_pdv_venda integer NOT NULL REFERENCES public.pdv_vendas (id_pdv_venda),
    id_pdv_venda_recebimento integer REFERENCES public.pdv_vendas_recebimentos (id_pdv_venda_recebimento),
    id_pdv_cliente integer REFERENCES public.pdv_clientes (id_pdv_cliente),
    nome_cliente character varying,
    data_envio date NOT NULL,
    valor numeric(14,2) NOT NULL DEFAULT 0,
    valor_conciliado numeric(14,2) NOT NULL DEFAULT 0,
    -- ABERTA | CONCILIADA
    situacao character varying NOT NULL DEFAULT 'ABERTA',
    observacao text,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_consignacoes ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS ix_pdv_consignacoes_situacao ON public.pdv_consignacoes (cod_empresa, situacao);


-- ─── PERMISSÕES ──────────────────────────────────────────────────────────────
-- Sistema PDV, faixa 1600+. Nenhuma é concedida a ninguém aqui: só o
-- superusuário enxerga, por bypass.

INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo)
SELECT 'PDV', v.opcao, v.descricao, v.ordem, TRUE
FROM (VALUES
    ('MENU',                'Menu do PDV Matrix',            1600),
    ('VENDER',              'Realizar Vendas (PDV)',         1610),
    ('CONSULTAR_VENDAS',    'Consultar Vendas',              1620),
    ('CADASTROS',           'Cadastros do PDV',              1630),
    ('CLIENTES',            'Cadastro de Clientes',          1640),
    ('PRODUTOS',            'Cadastro de Produtos',          1650),
    ('VENDEDORES',          'Cadastro de Vendedores',        1660),
    ('CONTAS_FINANCEIRAS',  'Cadastro de Contas Financeiras', 1670),
    ('OPERADORAS_CARTAO',   'Cadastro de Operadoras de Cartão', 1680),
    ('LANCAMENTOS',         'Lançamentos do Fluxo de Caixa', 1690),
    ('NOTAS_PRAZO',         'Recebimento de Notas a Prazo',  1700),
    ('CAIXA_CENTRAL',       'Caixa Central de Vendas',       1710)
) AS v(opcao, descricao, ordem)
WHERE NOT EXISTS (
    SELECT 1 FROM permissoes_catalogo p
    WHERE p.sistema = 'PDV' AND p.opcao = v.opcao
);
