-- =====================================================================
-- Saldos — importação de Perdas e Sobras (bloco Valores Informados)
--
-- Mesmo critério das importações de Compra de Combustível, Em Trânsito e
-- Estoque: os números saem da Consulta de Estoques (coluna perda_sobra_rs)
-- e só podem ser puxados quando TUDO está bloqueado em Operações até a
-- data. Uma linha aqui = aquele campo, naquela data e área, veio de
-- importação: os campos ficam travados e o botão vira "Desfazer importação".
--
-- Tabela separada de saldos_importacoes_estoque porque ali a chave é o
-- indicador de recebível (FK), e Perdas e Sobras é uma COLUNA de
-- valores_informados, não um indicador.
-- =====================================================================

CREATE TABLE IF NOT EXISTS saldos_importacoes_informados (
    id_importacao   integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa     character varying NOT NULL,
    data            date NOT NULL,
    id_area         integer NOT NULL,
    campo           character varying NOT NULL,   -- coluna de valores_informados (hoje: perdas_sobras)
    id_usuario      integer,
    criado_em       timestamp without time zone DEFAULT now(),
    CONSTRAINT uq_saldos_importacoes_informados UNIQUE (cod_empresa, data, id_area, campo)
);

CREATE INDEX IF NOT EXISTS idx_saldos_importacoes_informados_empresa_data
    ON saldos_importacoes_informados (cod_empresa, data, id_area);

ALTER TABLE saldos_importacoes_informados ENABLE ROW LEVEL SECURITY;
