-- CR Cartões — totalização por bandeira
--
-- O arquivo "Movimentação de Cartões" traz a bandeira na coluna Administradora
-- (AMEX, ELO CREDITO, MASTER CREDITO…). A importação já somava o Total Líquido
-- por filial em cartoes_filiais; agora soma também por filial × bandeira aqui,
-- na mesma transação. A soma desta tabela numa importação fecha com
-- cartoes_importacoes.total_geral.
--
-- Guardado por filial (e não só por bandeira) para as telas poderem filtrar
-- por área. Importações anteriores a esta tabela não têm bandeira: o arquivo
-- não é guardado, só reimportando.

CREATE TABLE IF NOT EXISTS public.cartoes_bandeiras (
    id_cartao_bandeira  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_importacao       integer NOT NULL REFERENCES public.cartoes_importacoes(id) ON DELETE CASCADE,
    cod_empresa         character varying NOT NULL,
    nome_filial_import  character varying NOT NULL,
    bandeira            character varying NOT NULL,
    saldo               numeric(15,2) NOT NULL DEFAULT 0,
    criado_em           timestamp without time zone DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_cartoes_bandeiras_importacao
    ON public.cartoes_bandeiras (id_importacao);

ALTER TABLE public.cartoes_bandeiras ENABLE ROW LEVEL SECURITY;

-- Permissões: uma para a posição atual (tabela + pizza), outra para a
-- variação no tempo — mesmo par de Consultar / Variações do menu.
INSERT INTO public.permissoes_catalogo (sistema, opcao, descricao, ordem, ativo)
SELECT 'FINANCEIRO', v.opcao, v.descricao, v.ordem, TRUE
  FROM (VALUES
    ('CARTOES_BANDEIRAS',           'CR Cartões — Posição por Bandeira',  1480),
    ('CARTOES_BANDEIRAS_VARIACOES', 'CR Cartões — Variações por Bandeira', 1490)
  ) AS v(opcao, descricao, ordem)
 WHERE NOT EXISTS (SELECT 1 FROM public.permissoes_catalogo p
                    WHERE p.sistema = 'FINANCEIRO' AND p.opcao = v.opcao);

-- Quem já consulta os cartões por filial passa a ver por bandeira: é o mesmo
-- dado, só agrupado de outro jeito.
INSERT INTO public.usuarios_permissoes (id_usuario, cod_empresa, sistema, opcao, ativo)
SELECT up.id_usuario, up.cod_empresa, 'FINANCEIRO', m.nova, up.ativo
  FROM public.usuarios_permissoes up
  JOIN (VALUES ('CARTOES_CONSULTAR', 'CARTOES_BANDEIRAS'),
               ('CARTOES_VARIACOES', 'CARTOES_BANDEIRAS_VARIACOES')) AS m(antiga, nova)
    ON up.sistema = 'FINANCEIRO' AND up.opcao = m.antiga
 WHERE NOT EXISTS (SELECT 1 FROM public.usuarios_permissoes x
                    WHERE x.id_usuario = up.id_usuario AND x.cod_empresa = up.cod_empresa
                      AND x.sistema = 'FINANCEIRO' AND x.opcao = m.nova);
