-- =====================================================================
-- Conferir Caixas — quais colunas de forma de recebimento ficam abertas
--
-- Cada filial escolhe quais formas de recebimento aparecem na grade. A
-- coluna fechada não some: vira uma tira fina que continua segurando o
-- checkbox, então dá pra reabrir no mesmo lugar.
--
-- Regra de preenchimento (aplicada na rota, não aqui):
--   - sem linha nesta tabela = primeira visita; o estado inicial vem do
--     próprio movimento (forma com valor no mês nasce aberta);
--   - com linha = a escolha manual do usuário manda;
--   - forma com valor lançado é sempre exibida e o checkbox fica travado,
--     pra nunca esconder dado real.
--
-- Guarda só a exceção e o que foi escolhido: uma linha por
-- (empresa, filial, forma).
-- =====================================================================

CREATE TABLE caixas_colunas_visiveis (
    id             integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_empresa    character varying NOT NULL,
    cod_filial     integer NOT NULL,
    id_forma       integer NOT NULL,
    visivel        boolean NOT NULL DEFAULT true,
    atualizado_em  timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT caixas_colunas_visiveis_unica
        UNIQUE (cod_empresa, cod_filial, id_forma)
);

CREATE INDEX idx_caixas_colunas_visiveis_filial
    ON caixas_colunas_visiveis (cod_empresa, cod_filial);

ALTER TABLE caixas_colunas_visiveis ENABLE ROW LEVEL SECURITY;

CREATE POLICY service_role_only ON caixas_colunas_visiveis
    FOR ALL TO service_role USING (true) WITH CHECK (true);
