-- Origem da importação de VENDAS DIÁRIAS, por empresa.
-- Coluna nova na mesma linha de vendas_parametros, separada da origem do
-- painel (sistema_origem_painel) para não misturar as duas importações.

ALTER TABLE vendas_parametros
    ADD COLUMN IF NOT EXISTS sistema_origem_diarias character varying NOT NULL DEFAULT 'WEBPOSTOS';

UPDATE vendas_parametros
   SET sistema_origem_diarias = 'OCLOSET',
       atualizado_em = now()
 WHERE cod_empresa = 'EMP013';

INSERT INTO vendas_parametros (cod_empresa, sistema_origem_painel, sistema_origem_diarias)
VALUES ('EMP013', 'OCLOSET', 'OCLOSET')
ON CONFLICT (cod_empresa) DO NOTHING;

-- O CSV do O Closet não traz código de produto, e vendas_diarias.codigo_produto
-- é inteiro. Esta tabela dá um código estável por descrição, para o mesmo
-- produto cair sempre no mesmo código entre importações.
CREATE TABLE IF NOT EXISTS vendas_produtos_ocloset (
    id_vendas_produto_ocloset integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    descricao character varying(100) NOT NULL,
    codigo_produto integer NOT NULL,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now(),
    UNIQUE (cod_empresa, descricao),
    UNIQUE (cod_empresa, codigo_produto)
);

ALTER TABLE vendas_produtos_ocloset ENABLE ROW LEVEL SECURITY;
