-- PDV Matrix — atributos de produto de loja de roupa e importação do estoque.
--
-- As colunas abaixo vêm do arquivo de estoque d'O Closet. Ficam TODAS no
-- cadastro do produto porque descrevem a peça, não o saldo.
--
-- O que NÃO entra como coluna, por ser calculado (regra do projeto: nada de
-- total/diferença persistido):
--
--   Disponível              = quantidade_atual − quantidade_reservada
--   Abaixo do mínimo        = disponível < estoque_minimo
--   Valor em estoque custo  = quantidade_atual × custo_atual
--   Valor em estoque venda  = quantidade_atual × preco_venda
--
-- "Vendido 30d/90d/12m" e "Última venda" também não entram: saem das vendas.

ALTER TABLE public.pdv_produtos
    ADD COLUMN IF NOT EXISTS marca character varying,
    ADD COLUMN IF NOT EXISTS categoria character varying,
    ADD COLUMN IF NOT EXISTS cor character varying,
    ADD COLUMN IF NOT EXISTS tamanho character varying,
    -- peças separadas para um cliente: saem do disponível, não do estoque
    ADD COLUMN IF NOT EXISTS quantidade_reservada numeric(14,3) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS estoque_minimo numeric(14,3) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS estoque_maximo numeric(14,3) NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS ix_pdv_produtos_marca
    ON public.pdv_produtos (cod_empresa, marca);
CREATE INDEX IF NOT EXISTS ix_pdv_produtos_categoria
    ON public.pdv_produtos (cod_empresa, categoria);


-- Uma linha por arquivo importado, para saber o que cada carga trouxe.
CREATE TABLE IF NOT EXISTS public.pdv_estoque_importacoes (
    id_pdv_estoque_importacao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    cod_filial integer NOT NULL,
    nome_arquivo character varying,
    data_referencia date NOT NULL,
    linhas integer NOT NULL DEFAULT 0,
    produtos_novos integer NOT NULL DEFAULT 0,
    produtos_atualizados integer NOT NULL DEFAULT 0,
    movimentos integer NOT NULL DEFAULT 0,
    pecas numeric(14,3) NOT NULL DEFAULT 0,
    id_usuario integer,
    nome_usuario character varying,
    criado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_estoque_importacoes ENABLE ROW LEVEL SECURITY;


INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo)
SELECT 'PDV', 'IMPORTAR_ESTOQUE', 'Importar Estoque (arquivo)', 1870, TRUE
WHERE NOT EXISTS (
    SELECT 1 FROM permissoes_catalogo
    WHERE sistema = 'PDV' AND opcao = 'IMPORTAR_ESTOQUE'
);
