-- Títulos manuais e Orçamento de Despesas — PDV Matrix.
--
-- ─── Por que o título manual NÃO tem tabela própria ──────────────────────────
--
-- Conta de luz, água e telefone geram a MESMA coisa que a nota de entrada
-- gera: uma obrigação a pagar, com vencimento, que um dia é baixada e vira
-- saída de caixa. Uma `pdv_titulos_manuais` separada partiria Contas a Pagar
-- em duas: o total em aberto, os vencidos e o fluxo de caixa projetado teriam
-- de somar duas fontes, e a primeira tela que esquecesse uma delas mentiria.
-- (É o mesmo raciocínio de `criar_pdv_caixa_diario.sql`.)
--
-- O que distingue o título manual é a ORIGEM, e origem é atributo:
--
--     NOTA_ENTRADA → nasceu da entrada de mercadoria (id_pdv_nota_entrada)
--     MANUAL       → digitado na tela de Títulos Manuais
--     ORCAMENTO    → gerado a partir da previsão do mês
--
-- ─── O que TEM tabela própria: o orçamento ───────────────────────────────────
--
-- Previsão não é obrigação. O valor previsto da luz de outubro não deve nada a
-- ninguém, não vence, não é baixado e não pode aparecer em Contas a Pagar —
-- se aparecesse, a empresa passaria a dever o que ainda nem consumiu. Por isso
-- `pdv_orcamento_despesas` é outra tabela, e o título só nasce quando alguém
-- confirma o mês (aí sim com origem ORCAMENTO, apontando para a previsão que
-- o originou — é assim que se compara previsto × realizado depois).

-- ─── TIPOS DE DESPESA ────────────────────────────────────────────────────────
-- O catálogo do que se paga todo mês. É por ele que a despesa se agrupa no
-- orçamento e na consulta.

CREATE TABLE IF NOT EXISTS public.pdv_despesas_tipos (
    id_pdv_despesa_tipo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    nome character varying NOT NULL,
    grupo character varying,                       -- Ocupação, Utilidades, Pessoal...
    id_pdv_fornecedor integer REFERENCES public.pdv_fornecedores (id_pdv_fornecedor),
    dia_vencimento integer,                        -- sugestão ao lançar/gerar
    ordem integer DEFAULT 10,
    ativo boolean NOT NULL DEFAULT TRUE,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_despesas_tipos ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX IF NOT EXISTS uq_pdv_despesas_tipos_nome
    ON public.pdv_despesas_tipos (cod_empresa, lower(nome));

-- ─── ORÇAMENTO DE DESPESAS ───────────────────────────────────────────────────
-- Uma linha por tipo/ano/mês. Só previsão: nada aqui é devido.

CREATE TABLE IF NOT EXISTS public.pdv_orcamento_despesas (
    id_pdv_orcamento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    id_pdv_despesa_tipo integer NOT NULL
        REFERENCES public.pdv_despesas_tipos (id_pdv_despesa_tipo),
    ano integer NOT NULL,
    mes integer NOT NULL,
    valor_previsto numeric(14,2) NOT NULL DEFAULT 0,
    observacao character varying,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);
ALTER TABLE public.pdv_orcamento_despesas ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX IF NOT EXISTS uq_pdv_orcamento_despesas
    ON public.pdv_orcamento_despesas (cod_empresa, id_pdv_despesa_tipo, ano, mes);

-- ─── TÍTULO A PAGAR: origem, tipo de despesa e competência ───────────────────
-- `competencia` é o mês A QUE a despesa se refere, que não é o do vencimento:
-- a luz de agosto vence em setembro. É por ela que a tela filtra o mês.

ALTER TABLE public.pdv_titulos_pagar
    ADD COLUMN IF NOT EXISTS origem character varying NOT NULL DEFAULT 'NOTA_ENTRADA';

ALTER TABLE public.pdv_titulos_pagar
    ADD COLUMN IF NOT EXISTS id_pdv_despesa_tipo integer
        REFERENCES public.pdv_despesas_tipos (id_pdv_despesa_tipo);

ALTER TABLE public.pdv_titulos_pagar
    ADD COLUMN IF NOT EXISTS id_pdv_orcamento integer
        REFERENCES public.pdv_orcamento_despesas (id_pdv_orcamento);

ALTER TABLE public.pdv_titulos_pagar
    ADD COLUMN IF NOT EXISTS competencia date;

ALTER TABLE public.pdv_titulos_pagar
    ADD COLUMN IF NOT EXISTS observacao character varying;

-- Os títulos que já existem vieram todos da entrada de mercadorias.
UPDATE public.pdv_titulos_pagar
   SET origem = 'NOTA_ENTRADA'
 WHERE origem IS NULL;

CREATE INDEX IF NOT EXISTS ix_pdv_titulos_pagar_origem
    ON public.pdv_titulos_pagar (cod_empresa, origem, competencia);

-- ─── PERMISSÕES ──────────────────────────────────────────────────────────────

INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo)
SELECT 'PDV', v.opcao, v.descricao, v.ordem, TRUE
FROM (VALUES
    ('TITULOS_MANUAIS', 'Entrada de títulos manuais', 1930),
    ('ORCAMENTO_DESPESAS', 'Orçamento de despesas', 1940),
    ('DESPESAS_TIPOS', 'Cadastro de tipos de despesa', 1950)
) AS v(opcao, descricao, ordem)
WHERE NOT EXISTS (
    SELECT 1 FROM permissoes_catalogo p
    WHERE p.sistema = 'PDV' AND p.opcao = v.opcao
);
