-- Empréstimos e Financiamentos — reconstrução completa (23/09/2026).
--
-- O modelo antigo (financeiro_emprestimos + _parcelas + _pagamentos, nunca
-- versionado em migration — existia só no banco) tinha carência, modalidade
-- de cálculo (PRICE/SAC/parcela fixa/juros variáveis) e indexador/spread —
-- indexador e spread nem chegavam a gravar (bug de campo perdido no POST).
-- Vira um modelo de planilha, a pedido do cliente: um contrato (empresa,
-- descrição, valor, quantidade de parcelas, data base do primeiro
-- vencimento) e uma parcela por linha (nº, vencimento, principal, juros,
-- pago). O total nunca é coluna — é sempre principal + juros, calculado na
-- consulta (convenção do projeto). A tabela de pagamentos separada também
-- some: o checkbox "pago" já é o registro.
--
-- As 3 tabelas antigas viram "_legado" (arquivo morto, RLS mantido, fora do
-- alcance da aplicação) em vez de serem apagadas de verdade: são 16
-- contratos reais da Vilela (EMP011) e da 30 Set CZ (EMP012) — R$ milhões de
-- passivo digitado à mão, sem seed nem migration para reconstruir se o DROP
-- desse errado.
--
-- A migração dos dados preserva id_emprestimo (OVERRIDING SYSTEM VALUE) para
-- as parcelas não precisarem de remapeamento de id_emprestimo. A
-- quantidade_parcelas do contrato novo é a contagem real de parcelas
-- migradas, não o "contratado" antigo — os contratos 17 e 18 tinham geração
-- parcial/carência e esse número nunca bateu com o que existia de fato.
-- instituição não vira campo próprio (decisão do cliente: fica dentro da
-- descrição), por isso é anexada com " — " na migração quando preenchida.

ALTER TABLE public.financeiro_emprestimos RENAME TO financeiro_emprestimos_legado;
ALTER TABLE public.financeiro_emprestimos_parcelas RENAME TO financeiro_emprestimos_parcelas_legado;
ALTER TABLE public.financeiro_emprestimos_pagamentos RENAME TO financeiro_emprestimos_pagamentos_legado;

-- RENAME TABLE não renomeia os índices/constraints da tabela — eles ficam
-- com o nome antigo mesmo depois do rename, e nome de índice é único no
-- schema inteiro (não só na tabela). Sem isso, os CREATE TABLE/INDEX das
-- tabelas novas abaixo colidem (foi o que aconteceu na primeira tentativa
-- desta migration: "idx_financeiro_emprestimos_empresa already exists").
ALTER INDEX financeiro_emprestimos_pkey RENAME TO financeiro_emprestimos_legado_pkey;
ALTER INDEX financeiro_emprestimos_empresa_codigo_unico RENAME TO financeiro_emprestimos_legado_empresa_codigo_unico;
ALTER INDEX idx_financeiro_emprestimos_empresa RENAME TO idx_financeiro_emprestimos_legado_empresa;
ALTER INDEX idx_financeiro_emprestimos_situacao RENAME TO idx_financeiro_emprestimos_legado_situacao;

ALTER INDEX financeiro_emprestimos_parcelas_pkey RENAME TO financeiro_emprestimos_parcelas_legado_pkey;
ALTER INDEX financeiro_emprestimos_parcelas_unica RENAME TO financeiro_emprestimos_parcelas_legado_unica;
ALTER INDEX idx_financeiro_emprestimos_parcelas_empresa RENAME TO idx_financeiro_emprestimos_parcelas_legado_empresa;
ALTER INDEX idx_financeiro_emprestimos_parcelas_emprestimo RENAME TO idx_financeiro_emprestimos_parcelas_legado_emprestimo;
ALTER INDEX idx_financeiro_emprestimos_parcelas_situacao RENAME TO idx_financeiro_emprestimos_parcelas_legado_situacao;
ALTER INDEX idx_financeiro_emprestimos_parcelas_vencimento RENAME TO idx_financeiro_emprestimos_parcelas_legado_vencimento;

ALTER INDEX financeiro_emprestimos_pagamentos_pkey RENAME TO financeiro_emprestimos_pagamentos_legado_pkey;
ALTER INDEX idx_financeiro_emprestimos_pagamentos_data RENAME TO idx_financeiro_emprestimos_pagamentos_legado_data;
ALTER INDEX idx_financeiro_emprestimos_pagamentos_emprestimo RENAME TO idx_financeiro_emprestimos_pagamentos_legado_emprestimo;
ALTER INDEX idx_financeiro_emprestimos_pagamentos_parcela RENAME TO idx_financeiro_emprestimos_pagamentos_legado_parcela;

COMMENT ON TABLE public.financeiro_emprestimos_legado IS
    'Arquivo morto do modelo antigo de Empréstimos e Financiamentos, substituído em 23/09/2026. Fora do alcance da aplicação — só consulta manual.';
COMMENT ON TABLE public.financeiro_emprestimos_parcelas_legado IS
    'Arquivo morto — ver financeiro_emprestimos_legado.';
COMMENT ON TABLE public.financeiro_emprestimos_pagamentos_legado IS
    'Arquivo morto — ver financeiro_emprestimos_legado.';

CREATE TABLE public.financeiro_emprestimos (
    id_emprestimo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_empresa character varying NOT NULL,
    descricao character varying NOT NULL,
    valor_contratado numeric NOT NULL DEFAULT 0,
    quantidade_parcelas integer NOT NULL DEFAULT 0,
    data_primeiro_vencimento date NOT NULL,
    ativo boolean NOT NULL DEFAULT true,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);

CREATE INDEX idx_financeiro_emprestimos_empresa
    ON public.financeiro_emprestimos (cod_empresa, ativo);

ALTER TABLE public.financeiro_emprestimos ENABLE ROW LEVEL SECURITY;


CREATE TABLE public.financeiro_emprestimos_parcelas (
    id_parcela integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_emprestimo integer NOT NULL REFERENCES public.financeiro_emprestimos (id_emprestimo),
    cod_empresa character varying NOT NULL,
    numero_parcela integer NOT NULL,
    data_vencimento date NOT NULL,
    valor_principal numeric NOT NULL DEFAULT 0,
    valor_juros numeric NOT NULL DEFAULT 0,
    pago boolean NOT NULL DEFAULT false,
    data_pagamento date,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone DEFAULT now()
);

CREATE INDEX idx_financeiro_emprestimos_parcelas_emprestimo
    ON public.financeiro_emprestimos_parcelas (id_emprestimo, numero_parcela);

ALTER TABLE public.financeiro_emprestimos_parcelas ENABLE ROW LEVEL SECURITY;


-- Permissões: já existiam no banco (ids 68/69), nunca tinham migration.
-- Mantém os mesmos nomes para não invalidar as concessões já feitas em
-- usuarios_permissoes (EMP011/EMP012). REGISTRAR_PAGAMENTOS_... não é
-- versionada: era usada só pela tela de Pagamentos separada, que deixou de
-- existir (o pagamento agora é o checkbox na própria parcela).
INSERT INTO permissoes_catalogo (sistema, opcao, descricao, ordem, ativo) VALUES
    ('FINANCEIRO', 'CADASTRO_EMPRESTIMOS_FINANCIAMENTOS', 'Empréstimos e Financiamentos - Cadastro', 610, true),
    ('FINANCEIRO', 'CONSULTA_EMPRESTIMOS_FINANCIAMENTOS', 'Empréstimos e Financiamentos - Consulta', 620, true)
ON CONFLICT DO NOTHING;


-- Migração dos 16 contratos / 1.004 parcelas reais (EMP011 e EMP012).
INSERT INTO public.financeiro_emprestimos (
    id_emprestimo, cod_empresa, descricao, valor_contratado,
    quantidade_parcelas, data_primeiro_vencimento, ativo, criado_em, atualizado_em
)
OVERRIDING SYSTEM VALUE
SELECT
    e.id_emprestimo,
    e.cod_empresa,
    e.descricao || CASE WHEN NULLIF(TRIM(e.instituicao), '') IS NOT NULL
                        THEN ' — ' || TRIM(e.instituicao) ELSE '' END,
    e.valor_contratado,
    COALESCE(qp.qtd, 0),
    e.data_primeiro_vencimento,
    e.ativo,
    e.criado_em,
    e.atualizado_em
FROM public.financeiro_emprestimos_legado e
LEFT JOIN (
    SELECT id_emprestimo, COUNT(*) AS qtd
    FROM public.financeiro_emprestimos_parcelas_legado
    GROUP BY id_emprestimo
) qp ON qp.id_emprestimo = e.id_emprestimo;

SELECT setval(
    pg_get_serial_sequence('public.financeiro_emprestimos', 'id_emprestimo'),
    COALESCE((SELECT MAX(id_emprestimo) FROM public.financeiro_emprestimos), 1)
);

INSERT INTO public.financeiro_emprestimos_parcelas (
    id_emprestimo, cod_empresa, numero_parcela, data_vencimento,
    valor_principal, valor_juros, pago, data_pagamento, criado_em, atualizado_em
)
SELECT
    id_emprestimo, cod_empresa, numero_parcela, data_vencimento,
    valor_principal, valor_juros, (situacao = 'PAGO'), data_pagamento, criado_em, atualizado_em
FROM public.financeiro_emprestimos_parcelas_legado
ORDER BY id_emprestimo, numero_parcela;
